$gwx_XC_14=function(_,_v,_n,_p,_s,_wp,_wl,$gwn,$gwl,$gwh,wh,$gstack,$gwrt,gra,grb,TestTest,wfor,_ca,_da,_r,_rz,_o,_oz,_1,_1z,_2,_2z,_m,_mz,nv_getDate,nv_getRegExp,nv_console,nv_parseInt,nv_parseFloat,nv_isNaN,nv_isFinite,nv_decodeURI,nv_decodeURIComponent,nv_encodeURI,nv_encodeURIComponent,$gdc,nv_JSON,_af,_gv,_ai,_grp,_gd,_gapi,$ixc,_ic,_w,_ev,_tsd){return function(path,global){
if(typeof global==='undefined'){if (typeof __GWX_GLOBAL__==='undefined')global={};else global=__GWX_GLOBAL__;}if(typeof __WXML_GLOBAL__ === 'undefined') {__WXML_GLOBAL__={};
}__WXML_GLOBAL__.modules = __WXML_GLOBAL__.modules || {};
var e_={}
if(typeof(global.entrys)==='undefined')global.entrys={};e_=global.entrys;
var d_={}
if(typeof(global.defines)==='undefined')global.defines={};d_=global.defines;
var f_={}
if(typeof(global.modules)==='undefined')global.modules={};f_=global.modules || {};
var p_={}
__WXML_GLOBAL__.ops_cached = __WXML_GLOBAL__.ops_cached || {}
__WXML_GLOBAL__.ops_set = __WXML_GLOBAL__.ops_set || {};
__WXML_GLOBAL__.ops_init = __WXML_GLOBAL__.ops_init || {};
var z=__WXML_GLOBAL__.ops_set.$gwx_XC_14 || [];
function gz$gwx_XC_14_1(){
if( __WXML_GLOBAL__.ops_cached.$gwx_XC_14_1)return __WXML_GLOBAL__.ops_cached.$gwx_XC_14_1
__WXML_GLOBAL__.ops_cached.$gwx_XC_14_1=[];
(function(z){var a=11;function Z(ops){z.push(ops)}
Z([3,'text-black'])
Z([3,'content'])
Z([3,'出行'])
Z([3,'bindRefresh'])
Z([3,'bindDownLoad'])
Z([[7],[3,'triggered']])
Z([a,[3,'height:calc(100vh - '],[[7],[3,'CustomBar']],[3,'px);']])
Z([[7],[3,'has_order']])
Z([[2,'=='],[[7],[3,'travelType']],[1,'order']])
Z([[7],[3,'orderList']])
Z([3,'orderId'])
Z([3,'orderDetail'])
Z([a,[3,'margin-lr-36 margin-bottom-sm radius-36 bg-white order-box position-relative '],[[7],[3,'globalStyle']]])
Z([[6],[[7],[3,'item']],[3,'orderTable']])
Z([[6],[[7],[3,'item']],[3,'orderId']])
Z([[6],[[7],[3,'item']],[3,'supplier']])
Z([[2,'=='],[[6],[[7],[3,'item']],[3,'orderTable']],[1,'gang_ao']])
Z([a,[3,'HMOrder bg-'],[[7],[3,'primary']],[3,' text-df padding-lr-sm']])
Z([3,'港澳订单'])
Z([3,'margin-bottom-sm'])
Z([3,' flex justify-between'])
Z([3,'text-xl color_333 text-bold'])
Z([a,[[6],[[7],[3,'item']],[3,'showDate']],[3,' '],[[6],[[7],[3,'item']],[3,'week']],[3,' '],[[6],[[7],[3,'item']],[3,'departTime']]])
Z([3,'padding-left-sm color_666 text-df'])
Z([a,[[7],[3,'interval_leave_name']]])
Z([3,'text-lg'])
Z([[2,'=='],[[6],[[7],[3,'item']],[3,'orderType']],[1,5]])
Z([3,'已取消'])
Z([a,[[6],[[7],[3,'item']],[3,'orderStatusTips']]])
Z([3,'padding-top-sm flex align-center justify-between'])
Z([3,'flex align-center'])
Z([a,[3,'schedule-icon bg-'],z[17][2]])
Z([3,'上'])
Z([3,'text-xl color_333'])
Z([a,[[6],[[7],[3,'item']],[3,'addressName']]])
Z([a,[3,'flight-money text-price text-'],z[17][2]])
Z([a,[[6],[[7],[3,'item']],[3,'priceFix']]])
Z(z[29])
Z(z[30])
Z([a,z[31][1],[[7],[3,'secondaryColor']]])
Z([3,'下'])
Z(z[33])
Z([a,[[6],[[7],[3,'item']],[3,'getOffAddressName']]])
Z([[6],[[7],[3,'item']],[3,'totalNumber']])
Z([3,'text-lg text-red nowrap'])
Z([a,[3,'票数：'],[[6],[[7],[3,'item']],[3,'totalNumber']]])
Z([[6],[[7],[3,'item']],[3,'backDate']])
Z([3,'padding-top-sm flex justify-between'])
Z(z[21])
Z([a,[[6],[[7],[3,'item']],[3,'showBackDate']],z[22][2],[[6],[[7],[3,'item']],[3,'backWeek']],z[22][2],[[6],[[7],[3,'item']],[3,'backTime']]])
Z(z[23])
Z([a,z[24][1]])
Z([[6],[[7],[3,'item']],[3,'backAddressName']])
Z(z[29])
Z(z[30])
Z([a,z[31][1],z[17][2]])
Z(z[32])
Z(z[33])
Z([a,[[6],[[7],[3,'item']],[3,'backAddressName']]])
Z([[6],[[7],[3,'item']],[3,'backGetOffAddressName']])
Z(z[29])
Z(z[30])
Z([a,z[31][1],z[39][2]])
Z(z[40])
Z(z[33])
Z([a,[[6],[[7],[3,'item']],[3,'backGetOffAddressName']]])
Z(z[47])
Z([3,'nowrap text-lg'])
Z([3,'text-gray margin-right-sm'])
Z([a,[[6],[[7],[3,'item']],[3,'orderId']]])
Z([[2,'||'],[[2,'=='],[[6],[[7],[3,'item']],[3,'orderType']],[1,2]],[[6],[[7],[3,'item']],[3,'backDate']]])
Z([3,'双程票'])
Z([[2,'=='],[[6],[[7],[3,'item']],[3,'orderType']],[1,6]])
Z([3,'text-yellow'])
Z([3,'已改签'])
Z([a,[3,'text-'],z[17][2],[3,' text-lg']])
Z([3,'订单详情'])
Z([3,'cuIcon-right margin-left-sm'])
Z([[2,'=='],[[7],[3,'travelType']],[1,'ticket']])
Z([[7],[3,'ticketList']])
Z([3,'ticketId'])
Z([3,'margin-lr-36 margin-bottom-sm radius-36 bg-white order-box'])
Z([3,'padding-bottom-sm flex justify-between'])
Z([3,'text-bold text-xl'])
Z([a,z[22][1],z[22][2],z[22][3],z[22][2],z[22][5]])
Z(z[23])
Z([a,z[24][1]])
Z(z[25])
Z([a,[[6],[[7],[3,'item']],[3,'ticketStatusName']]])
Z(z[29])
Z(z[30])
Z([a,z[31][1],z[17][2]])
Z(z[32])
Z(z[25])
Z([a,z[34][1]])
Z(z[29])
Z(z[30])
Z([a,z[31][1],z[39][2]])
Z(z[40])
Z(z[25])
Z([a,z[42][1]])
Z([3,'padding-top-sm flex justify-end'])
Z([3,'goTicketOrderDetail'])
Z([a,[3,'cu-btn round line-'],z[17][2],[3,' margin-left']])
Z([[6],[[7],[3,'item']],[3,'orderid']])
Z([[6],[[7],[3,'item']],[3,'orderType']])
Z([3,'item-hover'])
Z([3,'订单'])
Z([3,'showPreVerifyModal'])
Z([a,[3,'cu-btn  round margin-left-xl '],[[2,'?:'],[[2,'!'],[[6],[[7],[3,'item']],[3,'isActiveBtn']]],[1,'line-gray '],[1,'bg']],[3,'-'],z[17][2]])
Z([[6],[[7],[3,'item']],[3,'ifChecked']])
Z([[6],[[7],[3,'item']],[3,'takeDate']])
Z([[6],[[7],[3,'item']],[3,'ticketStatusName']])
Z(z[104])
Z([[6],[[7],[3,'item']],[3,'ticketStatus']])
Z([[6],[[7],[3,'item']],[3,'ticketId']])
Z(z[106])
Z([3,'检票'])
Z([3,'padding'])
Z(z[118])
Z(z[118])
Z([[2,'!'],[[7],[3,'has_order']]])
Z([3,'null-wrap'])
Z([3,'null-main'])
Z([3,'null-content'])
Z([a,[[7],[3,'topTitle']]])
Z([3,'null-steps-list'])
Z([3,'steps-item'])
Z([3,'steps-item-dot'])
Z([3,'1'])
Z([3,'steps-item-line'])
Z([3,'steps-item-tit'])
Z([a,[[7],[3,'stepOneTitle']]])
Z([3,'steps-item-con'])
Z([a,[[7],[3,'stepOneSubTitle']]])
Z(z[127])
Z(z[128])
Z([3,'2'])
Z(z[130])
Z(z[131])
Z([a,[[7],[3,'stepTwoTitle']]])
Z(z[133])
Z([a,[[7],[3,'stepTwoSubTitle']]])
Z(z[127])
Z(z[128])
Z([3,'3'])
Z(z[130])
Z(z[131])
Z([3,'乘车出行'])
Z(z[133])
Z([3,'发车前到达上车站点乘车'])
Z([3,'gotoIndex'])
Z([3,'flex justify-center'])
Z([a,[3,'btn-size-radius bg-'],z[17][2]])
Z([3,'button-hover'])
Z([a,[[7],[3,'buyTicketName']]])
Z([a,[3,'cu-modal '],[[2,'?:'],[[2,'=='],[[7],[3,'modalName']],[1,'preVerifyModal']],[1,'show'],[1,'']]])
Z([3,'cu-dialog bg-white preVerifyDialog'])
Z([a,[3,'padding text-lg '],[[2,'?:'],[[7],[3,'isHoveImage']],[1,'text-bold'],[1,'']]])
Z([3,'长按图片1秒钟，可解锁车票'])
Z([[2,'!=='],[[7],[3,'progressStatus']],[1,2]])
Z([a,[3,'bg-'],z[17][2],[3,' animationProgress']])
Z([a,z[161][1],z[17][2],[3,' animationProgressBack']])
Z([3,'handleLongtap'])
Z([3,'handleClick'])
Z([3,'handleTouchEnd'])
Z([3,'handleTouchstart'])
Z(z[118])
Z([3,'padding-bottom text-df text-center'])
Z([3,'车票解锁后不能退票，请谨慎操作'])
Z(z[152])
Z([3,'verify-modal-image margin-right'])
Z([3,'aspectFit'])
Z([a,[3,'../../images/icon_ticket_'],[[2,'?:'],[[7],[3,'isHoveImage']],[1,'blue'],[1,'gray']],[3,'.png']])
Z([3,'verify-modal-image'])
Z(z[172])
Z([a,[3,'../../images/icon_finger_prict_'],z[173][2],z[173][3]])
Z([3,'cu-bar bg-white'])
Z([3,'action'])
Z([3,'hideModal'])
Z([3,'cu-btn round bg-gray'])
Z([3,'关闭'])
Z([3,'cx'])
})(__WXML_GLOBAL__.ops_cached.$gwx_XC_14_1);return __WXML_GLOBAL__.ops_cached.$gwx_XC_14_1
}
__WXML_GLOBAL__.ops_set.$gwx_XC_14=z;
__WXML_GLOBAL__.ops_init.$gwx_XC_14=true;
var x=['./pages/cx/cx.wxml'];d_[x[0]]={}
var m0=function(e,s,r,gg){
var z=gz$gwx_XC_14_1()
var o4NB=_n('cu-nav')
var x5NB=_mz(z,'view',['class',0,'slot',1],[],e,s,gg)
var o6NB=_oz(z,2,e,s,gg)
_(x5NB,o6NB)
_(o4NB,x5NB)
_(r,o4NB)
var f7NB=_mz(z,'scroll-view',['enableBackToTop',-1,'refresherEnabled',-1,'scrollY',-1,'bindrefresherrefresh',3,'bindscrolltolower',1,'refresherTriggered',2,'style',3],[],e,s,gg)
var c8NB=_v()
_(f7NB,c8NB)
if(_oz(z,7,e,s,gg)){c8NB.wxVkey=1
var h9NB=_v()
_(c8NB,h9NB)
if(_oz(z,8,e,s,gg)){h9NB.wxVkey=1
var o0NB=_v()
_(h9NB,o0NB)
var cAOB=function(lCOB,oBOB,aDOB,gg){
var eFOB=_mz(z,'view',['bindtap',11,'class',1,'data-order-Table',2,'data-orderid',3,'data-supplier',4],[],lCOB,oBOB,gg)
var bGOB=_v()
_(eFOB,bGOB)
if(_oz(z,16,lCOB,oBOB,gg)){bGOB.wxVkey=1
var fKOB=_n('view')
_rz(z,fKOB,'class',17,lCOB,oBOB,gg)
var cLOB=_oz(z,18,lCOB,oBOB,gg)
_(fKOB,cLOB)
_(bGOB,fKOB)
var hMOB=_n('view')
_rz(z,hMOB,'class',19,lCOB,oBOB,gg)
_(bGOB,hMOB)
}
var oNOB=_n('view')
_rz(z,oNOB,'class',20,lCOB,oBOB,gg)
var cOOB=_n('view')
var oPOB=_n('text')
_rz(z,oPOB,'class',21,lCOB,oBOB,gg)
var lQOB=_oz(z,22,lCOB,oBOB,gg)
_(oPOB,lQOB)
_(cOOB,oPOB)
var aROB=_n('text')
_rz(z,aROB,'class',23,lCOB,oBOB,gg)
var tSOB=_oz(z,24,lCOB,oBOB,gg)
_(aROB,tSOB)
_(cOOB,aROB)
_(oNOB,cOOB)
var eTOB=_n('view')
_rz(z,eTOB,'class',25,lCOB,oBOB,gg)
var bUOB=_v()
_(eTOB,bUOB)
if(_oz(z,26,lCOB,oBOB,gg)){bUOB.wxVkey=1
var oVOB=_n('text')
var xWOB=_oz(z,27,lCOB,oBOB,gg)
_(oVOB,xWOB)
_(bUOB,oVOB)
}
else{bUOB.wxVkey=2
var oXOB=_n('text')
var fYOB=_oz(z,28,lCOB,oBOB,gg)
_(oXOB,fYOB)
_(bUOB,oXOB)
}
bUOB.wxXCkey=1
_(oNOB,eTOB)
_(eFOB,oNOB)
var cZOB=_n('view')
_rz(z,cZOB,'class',29,lCOB,oBOB,gg)
var h1OB=_n('view')
_rz(z,h1OB,'class',30,lCOB,oBOB,gg)
var o2OB=_n('text')
_rz(z,o2OB,'class',31,lCOB,oBOB,gg)
var c3OB=_oz(z,32,lCOB,oBOB,gg)
_(o2OB,c3OB)
_(h1OB,o2OB)
var o4OB=_n('text')
_rz(z,o4OB,'class',33,lCOB,oBOB,gg)
var l5OB=_oz(z,34,lCOB,oBOB,gg)
_(o4OB,l5OB)
_(h1OB,o4OB)
_(cZOB,h1OB)
var a6OB=_n('view')
_rz(z,a6OB,'class',35,lCOB,oBOB,gg)
var t7OB=_oz(z,36,lCOB,oBOB,gg)
_(a6OB,t7OB)
_(cZOB,a6OB)
_(eFOB,cZOB)
var e8OB=_n('view')
_rz(z,e8OB,'class',37,lCOB,oBOB,gg)
var o0OB=_n('view')
_rz(z,o0OB,'class',38,lCOB,oBOB,gg)
var xAPB=_n('text')
_rz(z,xAPB,'class',39,lCOB,oBOB,gg)
var oBPB=_oz(z,40,lCOB,oBOB,gg)
_(xAPB,oBPB)
_(o0OB,xAPB)
var fCPB=_n('text')
_rz(z,fCPB,'class',41,lCOB,oBOB,gg)
var cDPB=_oz(z,42,lCOB,oBOB,gg)
_(fCPB,cDPB)
_(o0OB,fCPB)
_(e8OB,o0OB)
var b9OB=_v()
_(e8OB,b9OB)
if(_oz(z,43,lCOB,oBOB,gg)){b9OB.wxVkey=1
var hEPB=_n('view')
_rz(z,hEPB,'class',44,lCOB,oBOB,gg)
var oFPB=_oz(z,45,lCOB,oBOB,gg)
_(hEPB,oFPB)
_(b9OB,hEPB)
}
b9OB.wxXCkey=1
_(eFOB,e8OB)
var oHOB=_v()
_(eFOB,oHOB)
if(_oz(z,46,lCOB,oBOB,gg)){oHOB.wxVkey=1
var cGPB=_n('view')
_rz(z,cGPB,'class',47,lCOB,oBOB,gg)
var oHPB=_n('view')
var lIPB=_n('text')
_rz(z,lIPB,'class',48,lCOB,oBOB,gg)
var aJPB=_oz(z,49,lCOB,oBOB,gg)
_(lIPB,aJPB)
_(oHPB,lIPB)
var tKPB=_n('text')
_rz(z,tKPB,'class',50,lCOB,oBOB,gg)
var eLPB=_oz(z,51,lCOB,oBOB,gg)
_(tKPB,eLPB)
_(oHPB,tKPB)
_(cGPB,oHPB)
_(oHOB,cGPB)
}
var xIOB=_v()
_(eFOB,xIOB)
if(_oz(z,52,lCOB,oBOB,gg)){xIOB.wxVkey=1
var bMPB=_n('view')
_rz(z,bMPB,'class',53,lCOB,oBOB,gg)
var oNPB=_n('view')
_rz(z,oNPB,'class',54,lCOB,oBOB,gg)
var xOPB=_n('text')
_rz(z,xOPB,'class',55,lCOB,oBOB,gg)
var oPPB=_oz(z,56,lCOB,oBOB,gg)
_(xOPB,oPPB)
_(oNPB,xOPB)
var fQPB=_n('text')
_rz(z,fQPB,'class',57,lCOB,oBOB,gg)
var cRPB=_oz(z,58,lCOB,oBOB,gg)
_(fQPB,cRPB)
_(oNPB,fQPB)
_(bMPB,oNPB)
_(xIOB,bMPB)
}
var oJOB=_v()
_(eFOB,oJOB)
if(_oz(z,59,lCOB,oBOB,gg)){oJOB.wxVkey=1
var hSPB=_n('view')
_rz(z,hSPB,'class',60,lCOB,oBOB,gg)
var oTPB=_n('view')
_rz(z,oTPB,'class',61,lCOB,oBOB,gg)
var cUPB=_n('text')
_rz(z,cUPB,'class',62,lCOB,oBOB,gg)
var oVPB=_oz(z,63,lCOB,oBOB,gg)
_(cUPB,oVPB)
_(oTPB,cUPB)
var lWPB=_n('text')
_rz(z,lWPB,'class',64,lCOB,oBOB,gg)
var aXPB=_oz(z,65,lCOB,oBOB,gg)
_(lWPB,aXPB)
_(oTPB,lWPB)
_(hSPB,oTPB)
_(oJOB,hSPB)
}
var tYPB=_n('view')
_rz(z,tYPB,'class',66,lCOB,oBOB,gg)
var eZPB=_n('view')
_rz(z,eZPB,'class',67,lCOB,oBOB,gg)
var o2PB=_n('text')
_rz(z,o2PB,'class',68,lCOB,oBOB,gg)
var x3PB=_oz(z,69,lCOB,oBOB,gg)
_(o2PB,x3PB)
_(eZPB,o2PB)
var b1PB=_v()
_(eZPB,b1PB)
if(_oz(z,70,lCOB,oBOB,gg)){b1PB.wxVkey=1
var o4PB=_n('text')
var f5PB=_oz(z,71,lCOB,oBOB,gg)
_(o4PB,f5PB)
_(b1PB,o4PB)
}
else if(_oz(z,72,lCOB,oBOB,gg)){b1PB.wxVkey=2
var c6PB=_n('text')
_rz(z,c6PB,'class',73,lCOB,oBOB,gg)
var h7PB=_oz(z,74,lCOB,oBOB,gg)
_(c6PB,h7PB)
_(b1PB,c6PB)
}
b1PB.wxXCkey=1
_(tYPB,eZPB)
var o8PB=_n('view')
_rz(z,o8PB,'class',75,lCOB,oBOB,gg)
var c9PB=_oz(z,76,lCOB,oBOB,gg)
_(o8PB,c9PB)
var o0PB=_n('text')
_rz(z,o0PB,'class',77,lCOB,oBOB,gg)
_(o8PB,o0PB)
_(tYPB,o8PB)
_(eFOB,tYPB)
bGOB.wxXCkey=1
oHOB.wxXCkey=1
xIOB.wxXCkey=1
oJOB.wxXCkey=1
_(aDOB,eFOB)
return aDOB
}
o0NB.wxXCkey=2
_2z(z,9,cAOB,e,s,gg,o0NB,'item','index','orderId')
}
else if(_oz(z,78,e,s,gg)){h9NB.wxVkey=2
var lAQB=_v()
_(h9NB,lAQB)
var aBQB=function(eDQB,tCQB,bEQB,gg){
var xGQB=_n('view')
_rz(z,xGQB,'class',81,eDQB,tCQB,gg)
var oHQB=_n('view')
_rz(z,oHQB,'class',82,eDQB,tCQB,gg)
var fIQB=_n('view')
var cJQB=_n('text')
_rz(z,cJQB,'class',83,eDQB,tCQB,gg)
var hKQB=_oz(z,84,eDQB,tCQB,gg)
_(cJQB,hKQB)
_(fIQB,cJQB)
var oLQB=_n('text')
_rz(z,oLQB,'class',85,eDQB,tCQB,gg)
var cMQB=_oz(z,86,eDQB,tCQB,gg)
_(oLQB,cMQB)
_(fIQB,oLQB)
_(oHQB,fIQB)
var oNQB=_n('view')
_rz(z,oNQB,'class',87,eDQB,tCQB,gg)
var lOQB=_oz(z,88,eDQB,tCQB,gg)
_(oNQB,lOQB)
_(oHQB,oNQB)
_(xGQB,oHQB)
var aPQB=_n('view')
_rz(z,aPQB,'class',89,eDQB,tCQB,gg)
var tQQB=_n('view')
_rz(z,tQQB,'class',90,eDQB,tCQB,gg)
var eRQB=_n('text')
_rz(z,eRQB,'class',91,eDQB,tCQB,gg)
var bSQB=_oz(z,92,eDQB,tCQB,gg)
_(eRQB,bSQB)
_(tQQB,eRQB)
var oTQB=_n('text')
_rz(z,oTQB,'class',93,eDQB,tCQB,gg)
var xUQB=_oz(z,94,eDQB,tCQB,gg)
_(oTQB,xUQB)
_(tQQB,oTQB)
_(aPQB,tQQB)
_(xGQB,aPQB)
var oVQB=_n('view')
_rz(z,oVQB,'class',95,eDQB,tCQB,gg)
var fWQB=_n('view')
_rz(z,fWQB,'class',96,eDQB,tCQB,gg)
var cXQB=_n('text')
_rz(z,cXQB,'class',97,eDQB,tCQB,gg)
var hYQB=_oz(z,98,eDQB,tCQB,gg)
_(cXQB,hYQB)
_(fWQB,cXQB)
var oZQB=_n('text')
_rz(z,oZQB,'class',99,eDQB,tCQB,gg)
var c1QB=_oz(z,100,eDQB,tCQB,gg)
_(oZQB,c1QB)
_(fWQB,oZQB)
_(oVQB,fWQB)
_(xGQB,oVQB)
var o2QB=_n('view')
_rz(z,o2QB,'class',101,eDQB,tCQB,gg)
var l3QB=_mz(z,'view',['bindtap',102,'class',1,'data-orderid',2,'data-type',3,'hoverClass',4],[],eDQB,tCQB,gg)
var a4QB=_oz(z,107,eDQB,tCQB,gg)
_(l3QB,a4QB)
_(o2QB,l3QB)
var t5QB=_mz(z,'view',['bindtap',108,'class',1,'data-check',2,'data-date',3,'data-name',4,'data-orderid',5,'data-status',6,'data-ticketid',7,'hoverClass',8],[],eDQB,tCQB,gg)
var e6QB=_oz(z,117,eDQB,tCQB,gg)
_(t5QB,e6QB)
_(o2QB,t5QB)
_(xGQB,o2QB)
_(bEQB,xGQB)
return bEQB
}
lAQB.wxXCkey=2
_2z(z,79,aBQB,e,s,gg,lAQB,'item','index','ticketId')
}
var b7QB=_n('view')
_rz(z,b7QB,'class',118,e,s,gg)
_(c8NB,b7QB)
var o8QB=_n('view')
_rz(z,o8QB,'class',119,e,s,gg)
_(c8NB,o8QB)
var x9QB=_n('view')
_rz(z,x9QB,'class',120,e,s,gg)
_(c8NB,x9QB)
h9NB.wxXCkey=1
}
else if(_oz(z,121,e,s,gg)){c8NB.wxVkey=2
var o0QB=_n('view')
_rz(z,o0QB,'class',122,e,s,gg)
var fARB=_n('view')
_rz(z,fARB,'class',123,e,s,gg)
var cBRB=_n('view')
_rz(z,cBRB,'class',124,e,s,gg)
var hCRB=_oz(z,125,e,s,gg)
_(cBRB,hCRB)
_(fARB,cBRB)
var oDRB=_n('view')
_rz(z,oDRB,'class',126,e,s,gg)
var cERB=_n('view')
_rz(z,cERB,'class',127,e,s,gg)
var oFRB=_n('view')
_rz(z,oFRB,'class',128,e,s,gg)
var lGRB=_oz(z,129,e,s,gg)
_(oFRB,lGRB)
_(cERB,oFRB)
var aHRB=_n('view')
_rz(z,aHRB,'class',130,e,s,gg)
_(cERB,aHRB)
var tIRB=_n('view')
_rz(z,tIRB,'class',131,e,s,gg)
var eJRB=_oz(z,132,e,s,gg)
_(tIRB,eJRB)
_(cERB,tIRB)
var bKRB=_n('view')
_rz(z,bKRB,'class',133,e,s,gg)
var oLRB=_oz(z,134,e,s,gg)
_(bKRB,oLRB)
_(cERB,bKRB)
_(oDRB,cERB)
var xMRB=_n('view')
_rz(z,xMRB,'class',135,e,s,gg)
var oNRB=_n('view')
_rz(z,oNRB,'class',136,e,s,gg)
var fORB=_oz(z,137,e,s,gg)
_(oNRB,fORB)
_(xMRB,oNRB)
var cPRB=_n('view')
_rz(z,cPRB,'class',138,e,s,gg)
_(xMRB,cPRB)
var hQRB=_n('view')
_rz(z,hQRB,'class',139,e,s,gg)
var oRRB=_oz(z,140,e,s,gg)
_(hQRB,oRRB)
_(xMRB,hQRB)
var cSRB=_n('view')
_rz(z,cSRB,'class',141,e,s,gg)
var oTRB=_oz(z,142,e,s,gg)
_(cSRB,oTRB)
_(xMRB,cSRB)
_(oDRB,xMRB)
var lURB=_n('view')
_rz(z,lURB,'class',143,e,s,gg)
var aVRB=_n('view')
_rz(z,aVRB,'class',144,e,s,gg)
var tWRB=_oz(z,145,e,s,gg)
_(aVRB,tWRB)
_(lURB,aVRB)
var eXRB=_n('view')
_rz(z,eXRB,'class',146,e,s,gg)
_(lURB,eXRB)
var bYRB=_n('view')
_rz(z,bYRB,'class',147,e,s,gg)
var oZRB=_oz(z,148,e,s,gg)
_(bYRB,oZRB)
_(lURB,bYRB)
var x1RB=_n('view')
_rz(z,x1RB,'class',149,e,s,gg)
var o2RB=_oz(z,150,e,s,gg)
_(x1RB,o2RB)
_(lURB,x1RB)
_(oDRB,lURB)
_(fARB,oDRB)
_(o0QB,fARB)
var f3RB=_mz(z,'view',['bindtap',151,'class',1],[],e,s,gg)
var c4RB=_mz(z,'view',['class',153,'hoverClass',1],[],e,s,gg)
var h5RB=_oz(z,155,e,s,gg)
_(c4RB,h5RB)
_(f3RB,c4RB)
_(o0QB,f3RB)
_(c8NB,o0QB)
}
c8NB.wxXCkey=1
_(r,f7NB)
var o6RB=_n('view')
_rz(z,o6RB,'class',156,e,s,gg)
var c7RB=_n('view')
_rz(z,c7RB,'class',157,e,s,gg)
var l9RB=_n('view')
_rz(z,l9RB,'class',158,e,s,gg)
var a0RB=_oz(z,159,e,s,gg)
_(l9RB,a0RB)
_(c7RB,l9RB)
var o8RB=_v()
_(c7RB,o8RB)
if(_oz(z,160,e,s,gg)){o8RB.wxVkey=1
var tASB=_n('view')
_rz(z,tASB,'class',161,e,s,gg)
_(o8RB,tASB)
}
else{o8RB.wxVkey=2
var eBSB=_n('view')
_rz(z,eBSB,'class',162,e,s,gg)
_(o8RB,eBSB)
}
var bCSB=_mz(z,'view',['bindlongpress',163,'bindtap',1,'bindtouchend',2,'bindtouchstart',3,'class',4],[],e,s,gg)
var oDSB=_n('view')
_rz(z,oDSB,'class',168,e,s,gg)
var xESB=_oz(z,169,e,s,gg)
_(oDSB,xESB)
_(bCSB,oDSB)
var oFSB=_n('view')
_rz(z,oFSB,'class',170,e,s,gg)
var fGSB=_mz(z,'image',['class',171,'mode',1,'src',2],[],e,s,gg)
_(oFSB,fGSB)
var cHSB=_mz(z,'image',['class',174,'mode',1,'src',2],[],e,s,gg)
_(oFSB,cHSB)
_(bCSB,oFSB)
_(c7RB,bCSB)
var hISB=_n('view')
_rz(z,hISB,'class',177,e,s,gg)
var oJSB=_n('view')
_rz(z,oJSB,'class',178,e,s,gg)
var cKSB=_mz(z,'button',['bindtap',179,'class',1],[],e,s,gg)
var oLSB=_oz(z,181,e,s,gg)
_(cKSB,oLSB)
_(oJSB,cKSB)
_(hISB,oJSB)
_(c7RB,hISB)
o8RB.wxXCkey=1
_(o6RB,c7RB)
_(r,o6RB)
var lMSB=_n('index-float-btn')
_rz(z,lMSB,'pageName',182,e,s,gg)
_(r,lMSB)
return r
}
e_[x[0]]={f:m0,j:[],i:[],ti:[],ic:[]}
if(path&&e_[path]){
outerGlobal.__wxml_comp_version__=0.02
return function(env,dd,global){$gwxc=0;var root={"tag":"wx-page"};root.children=[]
;g="$gwx_XC_14";var main=e_[path].f
if (typeof global==="undefined")global={};global.f=$gdc(f_[path],"",1);
if(typeof(outerGlobal.__webview_engine_version__)!='undefined'&&outerGlobal.__webview_engine_version__+1e-6>=0.02+1e-6&&outerGlobal.__mergeData__)
{
env=outerGlobal.__mergeData__(env,dd);
}
try{
main(env,{},root,global);
_tsd(root)
if(typeof(outerGlobal.__webview_engine_version__)=='undefined'|| outerGlobal.__webview_engine_version__+1e-6<0.01+1e-6){return _ev(root);}
}catch(err){
console.log(err)
}
;g="";
return root;
}
}
}
}(__g.a,__g.b,__g.c,__g.d,__g.e,__g.f,__g.g,__g.h,__g.i,__g.j,__g.k,__g.l,__g.m,__g.n,__g.o,__g.p,__g.q,__g.r,__g.s,__g.t,__g.u,__g.v,__g.w,__g.x,__g.y,__g.z,__g.A,__g.B,__g.C,__g.D,__g.E,__g.F,__g.G,__g.H,__g.I,__g.J,__g.K,__g.L,__g.M,__g.N,__g.O,__g.P,__g.Q,__g.R,__g.S,__g.T,__g.U,__g.V,__g.W,__g.X,__g.Y,__g.Z,__g.aa);if(__vd_version_info__.delayedGwx||false)$gwx_XC_14();	if (__vd_version_info__.delayedGwx) __wxAppCode__['pages/cx/cx.wxml'] = [$gwx_XC_14, './pages/cx/cx.wxml'];else __wxAppCode__['pages/cx/cx.wxml'] = $gwx_XC_14( './pages/cx/cx.wxml' );
	
var noCss=typeof __vd_version_info__!=='undefined'&&__vd_version_info__.noCss===true;if(!noCss){__wxAppCode__['pages/cx/cx.wxss'] = setCssToHead([[2,"./colorui/main.wxss"],[2,"./colorui/icon.wxss"],".",[1],"order-box{padding:",[0,24]," ",[0,24]," ",[0,48]," ",[0,28],"}\n.",[1],"order-box .",[1],"schedule-icon{border-radius:50%;color:var(--color_fff);display:inline-block;font-size:",[0,22],";height:",[0,28],";line-height:",[0,28],";margin-right:",[0,16],";min-width:",[0,28],";text-align:center;width:",[0,28],"}\n.",[1],"flight-money{font-size:",[0,32],";height:",[0,50],";line-height:",[0,36],"}\n.",[1],"null-wrap{padding:",[0,60]," ",[0,20],";text-align:center}\n.",[1],"null-wrap .",[1],"null-steps-list .",[1],"steps-item:last-child .",[1],"steps-item-line{bottom:auto}\n.",[1],"null-wrap .",[1],"null-main{font-size:",[0,28],";text-align:center}\n.",[1],"null-wrap .",[1],"null-content{color:var(--color_999);font-size:",[0,28],"}\n.",[1],"null-steps-list{margin:",[0,40]," auto ",[0,80],";max-width:",[0,400],";text-align:left}\n.",[1],"null-steps-list .",[1],"steps-item{margin-bottom:",[0,20],";padding-left:",[0,40],";position:relative}\n.",[1],"null-steps-list .",[1],"steps-item-dot{background:#dfdfdf;border-radius:50%;color:var(--white);font-size:",[0,22],";height:",[0,32],";left:",[0,-18],";line-height:",[0,32],";position:absolute;text-align:center;top:",[0,4],";width:",[0,32],";z-index:2}\n.",[1],"null-steps-list .",[1],"steps-item-con{color:var(--color_999);font-size:",[0,24],"}\n.",[1],"null-steps-list .",[1],"steps-item-tit{color:var(--color_333);font-size:",[0,28],"}\n.",[1],"null-steps-list .",[1],"steps-item-line{border-right:",[0,2]," solid #dfdfdf;bottom:",[0,-20],";left:",[0,-4],";position:absolute;top:",[0,4],";width:0;z-index:1}\n.",[1],"btn-size-radius{border-radius:",[0,44],";height:",[0,88],";line-height:",[0,88],";width:",[0,300],"}\n.",[1],"cu-modal .",[1],"cu-dialog .",[1],"verify-modal-image{height:",[0,200],";width:",[0,200],"}\n.",[1],"cu-modal .",[1],"cu-dialog .",[1],"animationProgress,.",[1],"cu-modal .",[1],"cu-dialog .",[1],"animationProgressBack{height:",[0,12],";width:",[0,0],"}\n.",[1],"item-hover{border:",[0,0],";color:var(--white);opacity:.8!important}\n.",[1],"order-box .",[1],"HMOrder{border-radius:",[0,24]," 0 ",[0,24]," 0;left:0;position:absolute;top:0}\n@media (prefers-color-scheme:dark){.",[1],"order-box{background:linear-gradient(180deg,#111,#111 60%,transparent)}\n}",],"Some selectors are not allowed in component wxss, including tag name selectors, ID selectors, and attribute selectors.(./pages/cx/cx.wxss:1:542)",{path:"./pages/cx/cx.wxss"});
}