$gwx_XC_6=function(_,_v,_n,_p,_s,_wp,_wl,$gwn,$gwl,$gwh,wh,$gstack,$gwrt,gra,grb,TestTest,wfor,_ca,_da,_r,_rz,_o,_oz,_1,_1z,_2,_2z,_m,_mz,nv_getDate,nv_getRegExp,nv_console,nv_parseInt,nv_parseFloat,nv_isNaN,nv_isFinite,nv_decodeURI,nv_decodeURIComponent,nv_encodeURI,nv_encodeURIComponent,$gdc,nv_JSON,_af,_gv,_ai,_grp,_gd,_gapi,$ixc,_ic,_w,_ev,_tsd){return function(path,global){
if(typeof global==='undefined'){if (typeof __GWX_GLOBAL__==='undefined')global={};else global=__GWX_GLOBAL__;}if(typeof __WXML_GLOBAL__ === 'undefined') {__WXML_GLOBAL__={};
}__WXML_GLOBAL__.modules = __WXML_GLOBAL__.modules || {};
var e_={}
if(typeof(global.entrys)==='undefined')global.entrys={};e_=global.entrys;
var d_={}
if(typeof(global.defines)==='undefined')global.defines={};d_=global.defines;
var f_={}
if(typeof(global.modules)==='undefined')global.modules={};f_=global.modules || {};
var p_={}
__WXML_GLOBAL__.ops_cached = __WXML_GLOBAL__.ops_cached || {}
__WXML_GLOBAL__.ops_set = __WXML_GLOBAL__.ops_set || {};
__WXML_GLOBAL__.ops_init = __WXML_GLOBAL__.ops_init || {};
var z=__WXML_GLOBAL__.ops_set.$gwx_XC_6 || [];
function gz$gwx_XC_6_1(){
if( __WXML_GLOBAL__.ops_cached.$gwx_XC_6_1)return __WXML_GLOBAL__.ops_cached.$gwx_XC_6_1
__WXML_GLOBAL__.ops_cached.$gwx_XC_6_1=[];
(function(z){var a=11;function Z(ops){z.push(ops)}
Z([3,'height:100vh;overflow:hidden;'])
Z([3,'cu-custom'])
Z([a,[3,'height:'],[[7],[3,'CustomBar']],[3,'px;margin-bottom:-'],[[7],[3,'CustomBar']],[3,'px']])
Z([a,[3,'cu-bar fixed text-white '],[[7],[3,'bgColor']]])
Z([a,z[2][1],z[2][2],[3,'px;padding-top:'],[[7],[3,'StatusBar']],[3,'px;'],[[2,'?:'],[[7],[3,'bgImage']],[[2,'+'],[[2,'+'],[1,'background-image:url('],[[7],[3,'bgImage']]],[1,')']],[1,'']]])
Z([3,'goMyOrderList'])
Z([3,'action'])
Z([3,'cuIcon-peoplefill color_000 padding-right-sm'])
Z([3,'content'])
Z([a,[3,'top:'],z[4][4],z[2][5]])
Z([3,'color_000'])
Z([a,[[7],[3,'corpName']]])
Z([3,'bindregionchange'])
Z([3,'map'])
Z([[7],[3,'latitude']])
Z([[7],[3,'longitude']])
Z([[7],[3,'markers']])
Z([[7],[3,'scale']])
Z([3,'width:100%;height:calc(100vh - 820rpx);'])
Z([3,'cover-icon-location text-center flex justify-center'])
Z([a,[3,'map_notice bg-'],[[7],[3,'primary']],[3,' padding-tb-xs padding-lr-sm']])
Z([a,[[7],[3,'mapPinNotice']]])
Z([a,[3,'cover-icon-location-pin cuIcon-locationfill text-'],z[20][2]])
Z([[7],[3,'isMapReady']])
Z([3,'move_to_my_location'])
Z([3,'cover-icon-my-location'])
Z([3,'button-hover'])
Z([a,[3,'cuIcon-focus text-'],z[20][2]])
Z([3,'new-control-panel bg-white'])
Z([3,'new-notice-box padding-sm flex align-center'])
Z([3,'icon-notice'])
Z([3,'../img/notice.png'])
Z([a,[3,'new-notice-text text-'],z[20][2]])
Z([a,[3,'亲爱的'],z[11][1],[3,'用户，祝您旅途愉快！']])
Z([3,'new-address-container'])
Z([3,'chooseLocation'])
Z([3,'flex align-center start-box padding-tb padding-lr-sm'])
Z([3,'start'])
Z([3,'geton'])
Z([3,'start-text text-lg'])
Z([[7],[3,'startAddress']])
Z([3,'start-othertext'])
Z([3,'在 '])
Z([3,'start-location'])
Z([a,[[7],[3,'startAddress']]])
Z(z[41])
Z([3,' 上车'])
Z(z[43])
Z([3,'请选择出发地'])
Z([3,'flex align-center padding-bottom padding-lr-sm'])
Z([3,'getoff'])
Z(z[35])
Z([3,'flex-sub end-text flex justify-between align-center'])
Z([3,'end'])
Z([a,[[2,'?:'],[[7],[3,'endAddress']],[[7],[3,'endAddress']],[1,'您要去哪儿']]])
Z([3,'onQueryBtnClick'])
Z([3,'text-lg query-btn text-center text-white'])
Z(z[26])
Z([3,'查询'])
Z([3,'padding-lr-sm search-history-box'])
Z([3,'handleClickHistoryBtn'])
Z([3,'index-search-history'])
Z([3,'panel-bottom'])
Z([3,'goCharterCar'])
Z([3,'btn-bottom flex-sub align-center'])
Z([3,'item-hover'])
Z([3,'icon-btn'])
Z([3,'../img/icon-left.png'])
Z([3,'bottom-text text-sm margin-left-xs'])
Z([3,'包车'])
Z(z[5])
Z(z[64])
Z(z[65])
Z([a,[3,'cuIcon-peoplefill padding-right-sm text-'],z[20][2]])
Z(z[68])
Z([3,'我的订单'])
Z([[7],[3,'canInvoice']])
Z([3,'getoInvoice'])
Z(z[64])
Z(z[65])
Z([3,'icon-btn icon_invoice'])
Z([3,'aspectFit'])
Z(z[68])
Z([3,'发票'])
Z([3,'previewBanner'])
Z([3,'banner'])
Z([a,[[7],[3,'staticHost']],[[7],[3,'bottomBannerUrl']]])
Z([3,'text-center margin-bottom-xs'])
Z([3,'support-text padding-tb-xs'])
Z([a,[3,'当前版本：'],[[7],[3,'version']]])
Z([[7],[3,'indexSupportName']])
Z([3,'text-center'])
Z(z[88])
Z([a,[[7],[3,'indexSupportName']]])
Z([3,'padding'])
Z([a,[3,'cu-modal '],[[2,'?:'],[[2,'=='],[[7],[3,'modalName']],[1,'applyForGetLocationModal']],[1,'show'],[1,'']]])
Z([3,'cu-dialog bg-white'])
Z([3,'flex justify-center margin text-lg'])
Z([3,'授权获取当前位置'])
Z([3,'margin padding-tb break-word text-left'])
Z([3,'申请使用您的当前位置，作为上车点。'])
Z([3,'请您仔细阅读并充分理解'])
Z([3,'openPrivacyContract'])
Z([a,[3,'text-'],z[20][2]])
Z([a,[[7],[3,'privacyContractName']]])
Z([3,'margin-top-sm'])
Z([3,'如果您不同意，将需要您手动选择上车点。'])
Z([3,'flex margin-tb justify-between'])
Z([3,'hideModal'])
Z([3,'cu-btn flex-sub margin-lr bg-gray round'])
Z([3,'不同意，手动选择'])
Z([3,'handleAgreeLoaction'])
Z([a,[3,'cu-btn flex-sub margin-lr bg-'],z[20][2],[3,' round']])
Z([3,'同意'])
})(__WXML_GLOBAL__.ops_cached.$gwx_XC_6_1);return __WXML_GLOBAL__.ops_cached.$gwx_XC_6_1
}
__WXML_GLOBAL__.ops_set.$gwx_XC_6=z;
__WXML_GLOBAL__.ops_init.$gwx_XC_6=true;
var x=['./package/indexCar2/indexCar2.wxml'];d_[x[0]]={}
var m0=function(e,s,r,gg){
var z=gz$gwx_XC_6_1()
var tSP=_n('view')
_rz(z,tSP,'style',0,e,s,gg)
var bUP=_mz(z,'view',['class',1,'style',1],[],e,s,gg)
var oVP=_mz(z,'view',['class',3,'style',1],[],e,s,gg)
var xWP=_mz(z,'view',['bindtap',5,'class',1],[],e,s,gg)
var oXP=_n('text')
_rz(z,oXP,'class',7,e,s,gg)
_(xWP,oXP)
_(oVP,xWP)
var fYP=_mz(z,'view',['class',8,'style',1],[],e,s,gg)
var cZP=_n('view')
_rz(z,cZP,'class',10,e,s,gg)
var h1P=_oz(z,11,e,s,gg)
_(cZP,h1P)
_(fYP,cZP)
_(oVP,fYP)
_(bUP,oVP)
_(tSP,bUP)
var o2P=_mz(z,'map',['showLocation',-1,'bindregionchange',12,'id',1,'latitude',2,'longitude',3,'markers',4,'scale',5,'style',6],[],e,s,gg)
var c3P=_n('view')
_rz(z,c3P,'class',19,e,s,gg)
var o4P=_n('view')
_rz(z,o4P,'class',20,e,s,gg)
var l5P=_oz(z,21,e,s,gg)
_(o4P,l5P)
_(c3P,o4P)
_(o2P,c3P)
var a6P=_n('text')
_rz(z,a6P,'class',22,e,s,gg)
_(o2P,a6P)
_(tSP,o2P)
var eTP=_v()
_(tSP,eTP)
if(_oz(z,23,e,s,gg)){eTP.wxVkey=1
var t7P=_mz(z,'view',['bindtap',24,'class',1,'hoverClass',2],[],e,s,gg)
var e8P=_n('text')
_rz(z,e8P,'class',27,e,s,gg)
_(t7P,e8P)
_(eTP,t7P)
}
var b9P=_n('view')
_rz(z,b9P,'class',28,e,s,gg)
var xAQ=_n('view')
_rz(z,xAQ,'class',29,e,s,gg)
var oBQ=_mz(z,'image',['class',30,'src',1],[],e,s,gg)
_(xAQ,oBQ)
var fCQ=_n('text')
_rz(z,fCQ,'class',32,e,s,gg)
var cDQ=_oz(z,33,e,s,gg)
_(fCQ,cDQ)
_(xAQ,fCQ)
_(b9P,xAQ)
var hEQ=_n('view')
_rz(z,hEQ,'class',34,e,s,gg)
var oFQ=_mz(z,'view',['bindtap',35,'class',1,'data-type',2],[],e,s,gg)
var cGQ=_n('view')
_rz(z,cGQ,'class',38,e,s,gg)
_(oFQ,cGQ)
var oHQ=_n('view')
_rz(z,oHQ,'class',39,e,s,gg)
var lIQ=_v()
_(oHQ,lIQ)
if(_oz(z,40,e,s,gg)){lIQ.wxVkey=1
var aJQ=_n('text')
_rz(z,aJQ,'class',41,e,s,gg)
var tKQ=_oz(z,42,e,s,gg)
_(aJQ,tKQ)
_(lIQ,aJQ)
var eLQ=_n('text')
_rz(z,eLQ,'class',43,e,s,gg)
var bMQ=_oz(z,44,e,s,gg)
_(eLQ,bMQ)
_(lIQ,eLQ)
var oNQ=_n('text')
_rz(z,oNQ,'class',45,e,s,gg)
var xOQ=_oz(z,46,e,s,gg)
_(oNQ,xOQ)
_(lIQ,oNQ)
}
else{lIQ.wxVkey=2
var oPQ=_n('text')
_rz(z,oPQ,'class',47,e,s,gg)
var fQQ=_oz(z,48,e,s,gg)
_(oPQ,fQQ)
_(lIQ,oPQ)
}
lIQ.wxXCkey=1
_(oFQ,oHQ)
_(hEQ,oFQ)
var cRQ=_n('view')
_rz(z,cRQ,'class',49,e,s,gg)
var hSQ=_n('view')
_rz(z,hSQ,'class',50,e,s,gg)
_(cRQ,hSQ)
var oTQ=_mz(z,'view',['bindtap',51,'class',1,'data-type',2],[],e,s,gg)
var cUQ=_n('view')
var oVQ=_oz(z,54,e,s,gg)
_(cUQ,oVQ)
_(oTQ,cUQ)
var lWQ=_mz(z,'view',['catch:tap',55,'class',1,'hoverClass',2],[],e,s,gg)
var aXQ=_oz(z,58,e,s,gg)
_(lWQ,aXQ)
_(oTQ,lWQ)
_(cRQ,oTQ)
_(hEQ,cRQ)
var tYQ=_n('view')
_rz(z,tYQ,'class',59,e,s,gg)
var eZQ=_mz(z,'index-search-history',['bind:clickHistoryBtn',60,'class',1],[],e,s,gg)
_(tYQ,eZQ)
_(hEQ,tYQ)
var b1Q=_n('view')
_rz(z,b1Q,'class',62,e,s,gg)
var x3Q=_mz(z,'view',['bindtap',63,'class',1,'hoverClass',2],[],e,s,gg)
var o4Q=_mz(z,'image',['class',66,'src',1],[],e,s,gg)
_(x3Q,o4Q)
var f5Q=_n('text')
_rz(z,f5Q,'class',68,e,s,gg)
var c6Q=_oz(z,69,e,s,gg)
_(f5Q,c6Q)
_(x3Q,f5Q)
_(b1Q,x3Q)
var h7Q=_mz(z,'view',['bindtap',70,'class',1,'hoverClass',2],[],e,s,gg)
var o8Q=_n('text')
_rz(z,o8Q,'class',73,e,s,gg)
_(h7Q,o8Q)
var c9Q=_n('text')
_rz(z,c9Q,'class',74,e,s,gg)
var o0Q=_oz(z,75,e,s,gg)
_(c9Q,o0Q)
_(h7Q,c9Q)
_(b1Q,h7Q)
var o2Q=_v()
_(b1Q,o2Q)
if(_oz(z,76,e,s,gg)){o2Q.wxVkey=1
var lAR=_mz(z,'view',['bindtap',77,'class',1,'hoverClass',2],[],e,s,gg)
var aBR=_mz(z,'image',['class',80,'mode',1],[],e,s,gg)
_(lAR,aBR)
var tCR=_n('text')
_rz(z,tCR,'class',82,e,s,gg)
var eDR=_oz(z,83,e,s,gg)
_(tCR,eDR)
_(lAR,tCR)
_(o2Q,lAR)
}
o2Q.wxXCkey=1
_(hEQ,b1Q)
_(b9P,hEQ)
var bER=_mz(z,'image',['bindtap',84,'class',1,'src',2],[],e,s,gg)
_(b9P,bER)
var oFR=_n('view')
_rz(z,oFR,'class',87,e,s,gg)
var xGR=_n('view')
_rz(z,xGR,'class',88,e,s,gg)
var oHR=_oz(z,89,e,s,gg)
_(xGR,oHR)
_(oFR,xGR)
_(b9P,oFR)
var o0P=_v()
_(b9P,o0P)
if(_oz(z,90,e,s,gg)){o0P.wxVkey=1
var fIR=_n('view')
_rz(z,fIR,'class',91,e,s,gg)
var cJR=_n('view')
_rz(z,cJR,'class',92,e,s,gg)
var hKR=_oz(z,93,e,s,gg)
_(cJR,hKR)
_(fIR,cJR)
_(o0P,fIR)
}
var oLR=_n('view')
_rz(z,oLR,'class',94,e,s,gg)
_(b9P,oLR)
o0P.wxXCkey=1
_(tSP,b9P)
var cMR=_n('view')
_rz(z,cMR,'class',95,e,s,gg)
var oNR=_n('view')
_rz(z,oNR,'class',96,e,s,gg)
var lOR=_n('view')
_rz(z,lOR,'class',97,e,s,gg)
var aPR=_oz(z,98,e,s,gg)
_(lOR,aPR)
_(oNR,lOR)
var tQR=_n('view')
_rz(z,tQR,'class',99,e,s,gg)
var eRR=_n('text')
var bSR=_oz(z,100,e,s,gg)
_(eRR,bSR)
_(tQR,eRR)
var oTR=_n('text')
var xUR=_oz(z,101,e,s,gg)
_(oTR,xUR)
_(tQR,oTR)
var oVR=_mz(z,'text',['bindtap',102,'class',1],[],e,s,gg)
var fWR=_oz(z,104,e,s,gg)
_(oVR,fWR)
_(tQR,oVR)
var cXR=_n('view')
_rz(z,cXR,'class',105,e,s,gg)
var hYR=_oz(z,106,e,s,gg)
_(cXR,hYR)
_(tQR,cXR)
_(oNR,tQR)
var oZR=_n('view')
_rz(z,oZR,'class',107,e,s,gg)
var c1R=_mz(z,'button',['bindtap',108,'class',1],[],e,s,gg)
var o2R=_oz(z,110,e,s,gg)
_(c1R,o2R)
_(oZR,c1R)
var l3R=_mz(z,'button',['bindtap',111,'class',1],[],e,s,gg)
var a4R=_oz(z,113,e,s,gg)
_(l3R,a4R)
_(oZR,l3R)
_(oNR,oZR)
_(cMR,oNR)
_(tSP,cMR)
eTP.wxXCkey=1
_(r,tSP)
return r
}
e_[x[0]]={f:m0,j:[],i:[],ti:[],ic:[]}
if(path&&e_[path]){
outerGlobal.__wxml_comp_version__=0.02
return function(env,dd,global){$gwxc=0;var root={"tag":"wx-page"};root.children=[]
;g="$gwx_XC_6";var main=e_[path].f
if (typeof global==="undefined")global={};global.f=$gdc(f_[path],"",1);
if(typeof(outerGlobal.__webview_engine_version__)!='undefined'&&outerGlobal.__webview_engine_version__+1e-6>=0.02+1e-6&&outerGlobal.__mergeData__)
{
env=outerGlobal.__mergeData__(env,dd);
}
try{
main(env,{},root,global);
_tsd(root)
if(typeof(outerGlobal.__webview_engine_version__)=='undefined'|| outerGlobal.__webview_engine_version__+1e-6<0.01+1e-6){return _ev(root);}
}catch(err){
console.log(err)
}
;g="";
return root;
}
}
}
}(__g.a,__g.b,__g.c,__g.d,__g.e,__g.f,__g.g,__g.h,__g.i,__g.j,__g.k,__g.l,__g.m,__g.n,__g.o,__g.p,__g.q,__g.r,__g.s,__g.t,__g.u,__g.v,__g.w,__g.x,__g.y,__g.z,__g.A,__g.B,__g.C,__g.D,__g.E,__g.F,__g.G,__g.H,__g.I,__g.J,__g.K,__g.L,__g.M,__g.N,__g.O,__g.P,__g.Q,__g.R,__g.S,__g.T,__g.U,__g.V,__g.W,__g.X,__g.Y,__g.Z,__g.aa);if(__vd_version_info__.delayedGwx||false)$gwx_XC_6();	if (__vd_version_info__.delayedGwx) __wxAppCode__['package/indexCar2/indexCar2.wxml'] = [$gwx_XC_6, './package/indexCar2/indexCar2.wxml'];else __wxAppCode__['package/indexCar2/indexCar2.wxml'] = $gwx_XC_6( './package/indexCar2/indexCar2.wxml' );
	
var noCss=typeof __vd_version_info__!=='undefined'&&__vd_version_info__.noCss===true;if(!noCss){__wxAppCode__['package/indexCar2/indexCar2.wxss'] = setCssToHead([[2,"./app.wxss"],[2,"./colorui/main.wxss"],[2,"./colorui/icon.wxss"],".",[1],"cover-bubble-item{position:absolute;top:",[0,16],";width:100%}\n.",[1],"cover-bubble-notice{border-radius:",[0,12],";opacity:.75}\n.",[1],"cover-bubble-close{height:",[0,32],";width:",[0,32],"}\n.",[1],"cover-icon-location{bottom:calc(50% + ",[0,60],");pointer-events:none;position:absolute;width:100%}\n.",[1],"map_notice{border-radius:",[0,29],";pointer-events:none}\n.",[1],"cover-icon-location-pin{font-size:",[0,60],";height:",[0,60],";left:calc(50% - ",[0,30],");pointer-events:none;position:absolute;top:calc(50% - ",[0,60],");width:",[0,60],"}\n.",[1],"cover-icon-my-location{background-color:var(--white);border-radius:",[0,10],";box-shadow:",[0,0]," ",[0,4]," ",[0,8]," rgba(0,0,0,.1);height:",[0,80],";margin-top:",[0,-120],";padding:",[0,8]," ",[0,10]," ",[0,10],";position:absolute;right:",[0,30],";width:",[0,80],"}\n.",[1],"cover-icon-my-location .",[1],"cuIcon-focus{font-size:",[0,60],"}\n.",[1],"footer-view-page{bottom:",[0,0],";box-shadow:",[0,0]," ",[0,0]," ",[0,8]," ",[0,0],";height:",[0,390],";max-height:",[0,420],";min-height:",[0,420],";overflow:hidden;position:absolute;width:100%;z-index:100}\n.",[1],"footer-view-page .",[1],"weui_btn{height:",[0,64],";letter-spacing:unset;line-height:",[0,64],";width:",[0,116],"}\n.",[1],"cu-bar{min-height:",[0,80],"}\n.",[1],"cu-bar .",[1],"search-form{margin:",[0,0],"}\n[class*\x3danimation-]{-webkit-animation-duration:.5s;animation-duration:.5s;-webkit-animation-fill-mode:both;animation-fill-mode:both;-webkit-animation-timing-function:ease-out;animation-timing-function:ease-out}\n.",[1],"animation-fade{-webkit-animation-duration:.8s;animation-duration:.8s;-webkit-animation-name:fade;animation-name:fade;-webkit-animation-timing-function:linear;animation-timing-function:linear}\n.",[1],"animation-reverse{animation-direction:reverse}\n@-webkit-keyframes fade{0%{opacity:0}\n100%{opacity:1}\n}@keyframes fade{0%{opacity:0}\n100%{opacity:1}\n}.",[1],"mask-box{height:",[0,40],";margin-bottom:",[0,-40],"}\n.",[1],"control-panel .",[1],"notice-box{background:#5397fd;border-radius:",[0,36]," ",[0,36]," ",[0,0]," ",[0,0],";box-shadow:",[0,-4]," ",[0,-6]," ",[0,18]," rgba(0,0,0,.1);height:",[0,96],"}\n.",[1],"control-panel .",[1],"notice-box wx-text{font-size:",[0,30],";height:",[0,96],";line-height:",[0,96],"}\n.",[1],"control-panel .",[1],"select-box{border-radius:",[0,36]," ",[0,36]," ",[0,0]," ",[0,0],";padding:",[0,20]," ",[0,42],"}\n.",[1],"address-container\x3e.",[1],"margin-left-54{margin-left:",[0,54],"}\n.",[1],"address-container\x3ewx-view .",[1],"cuIcon-title{font-size:",[0,42],";height:",[0,42],"}\n.",[1],"control-panel .",[1],"select-box .",[1],"address-container{margin:",[0,26]," ",[0,0]," ",[0,36],"}\n.",[1],"control-panel .",[1],"select-box .",[1],"address-container .",[1],"end-address-box{background:#f0f0f0;border-radius:",[0,16],";padding:",[0,36],"}\n.",[1],"control-panel .",[1],"select-box .",[1],"bottom-image-box{border-radius:",[0,36],";box-shadow:",[0,0]," ",[0,4]," ",[0,22]," rgba(0,0,0,.1);margin:",[0,0]," ",[0,0]," ",[0,6],";overflow:hidden}\n.",[1],"new-control-panel{border-radius:",[0,20]," ",[0,20]," ",[0,0]," ",[0,0],";padding:",[0,32]," ",[0,26]," ",[0,10],"}\n.",[1],"new-control-panel .",[1],"new-notice-box{background:rgba(219,238,255,.38);border-radius:",[0,12],";display:-webkit-flex;display:flex;height:",[0,58],"}\n.",[1],"new-control-panel .",[1],"new-notice-box .",[1],"icon-notice{height:",[0,26],";margin-right:",[0,18],";min-width:",[0,28],";width:",[0,28],"}\n.",[1],"new-control-panel .",[1],"new-notice-box .",[1],"new-notice-text{font-size:",[0,24],";font-weight:400}\n.",[1],"new-control-panel .",[1],"new-address-container{background:var(--white);border-radius:",[0,30],";margin-top:",[0,22],"}\n.",[1],"geton{background:#5397fd}\n.",[1],"getoff,.",[1],"geton{border-radius:50%;height:",[0,20],";min-width:",[0,20],";width:",[0,20],"}\n.",[1],"getoff{background:#ff8d1a}\n.",[1],"panel-bottom{background:linear-gradient(180deg,rgba(219,238,255,.38),hsla(0,0%,80%,0));border-radius:0 0,",[0,30],",",[0,30],";display:-webkit-flex;display:flex;-webkit-flex-direction:row;flex-direction:row;height:",[0,80],"}\n.",[1],"panel-bottom .",[1],"btn-bottom{display:-webkit-flex;display:flex;-webkit-justify-content:center;justify-content:center;line-height:",[0,80],"}\n.",[1],"panel-bottom .",[1],"btn-bottom .",[1],"icon-btn{height:",[0,30],";width:",[0,32],"}\n.",[1],"panel-bottom .",[1],"btn-bottom .",[1],"icon_invoice{background-image:url(https://static.ylxweb.com/web/xcx/images/user_center2023/icon_invoice_2023.png?v\x3d3);background-size:cover;display:inline-block;vertical-align:middle}\n.",[1],"start-text{margin-left:",[0,26],"}\n.",[1],"start-location{font-weight:",[0,32],";font-weight:700}\n.",[1],"start-othertext{color:#a6a6a6}\n.",[1],"end-text{background-color:rgba(206,231,255,.22);border:",[0,2]," solid #579aff;border-radius:10px;font-size:",[0,40],";font-weight:700;margin-left:",[0,26],";padding:",[0,18]," ",[0,24]," ",[0,18]," ",[0,40],"}\n.",[1],"query-btn{-webkit-align-items:center;align-items:center;background:linear-gradient(90deg,#579aff,#005eeb);border-radius:",[0,20],";display:-webkit-flex;display:flex;-webkit-flex-shrink:0;flex-shrink:0;-webkit-justify-content:center;justify-content:center;padding:",[0,14]," 0;width:",[0,150],"}\n.",[1],"new-control-panel .",[1],"banner{height:",[0,228],";padding-top:",[0,20],";width:100%}\n.",[1],"bottom-text{color:var(--color_666)}\n.",[1],"search-history-box{margin-left:",[0,46],"}\n",],"Some selectors are not allowed in component wxss, including tag name selectors, ID selectors, and attribute selectors.(./package/indexCar2/indexCar2.wxss:1:542)",{path:"./package/indexCar2/indexCar2.wxss"});
}