$gwx_XC_31=function(_,_v,_n,_p,_s,_wp,_wl,$gwn,$gwl,$gwh,wh,$gstack,$gwrt,gra,grb,TestTest,wfor,_ca,_da,_r,_rz,_o,_oz,_1,_1z,_2,_2z,_m,_mz,nv_getDate,nv_getRegExp,nv_console,nv_parseInt,nv_parseFloat,nv_isNaN,nv_isFinite,nv_decodeURI,nv_decodeURIComponent,nv_encodeURI,nv_encodeURIComponent,$gdc,nv_JSON,_af,_gv,_ai,_grp,_gd,_gapi,$ixc,_ic,_w,_ev,_tsd){return function(path,global){
if(typeof global==='undefined'){if (typeof __GWX_GLOBAL__==='undefined')global={};else global=__GWX_GLOBAL__;}if(typeof __WXML_GLOBAL__ === 'undefined') {__WXML_GLOBAL__={};
}__WXML_GLOBAL__.modules = __WXML_GLOBAL__.modules || {};
var e_={}
if(typeof(global.entrys)==='undefined')global.entrys={};e_=global.entrys;
var d_={}
if(typeof(global.defines)==='undefined')global.defines={};d_=global.defines;
var f_={}
if(typeof(global.modules)==='undefined')global.modules={};f_=global.modules || {};
var p_={}
__WXML_GLOBAL__.ops_cached = __WXML_GLOBAL__.ops_cached || {}
__WXML_GLOBAL__.ops_set = __WXML_GLOBAL__.ops_set || {};
__WXML_GLOBAL__.ops_init = __WXML_GLOBAL__.ops_init || {};
var z=__WXML_GLOBAL__.ops_set.$gwx_XC_31 || [];
function gz$gwx_XC_31_1(){
if( __WXML_GLOBAL__.ops_cached.$gwx_XC_31_1)return __WXML_GLOBAL__.ops_cached.$gwx_XC_31_1
__WXML_GLOBAL__.ops_cached.$gwx_XC_31_1=[];
(function(z){var a=11;function Z(ops){z.push(ops)}
Z([3,'data-v-45106d39'])
Z([3,'transparent'])
Z([3,'__l'])
Z(z[0])
Z([3,'#fff'])
Z([1,true])
Z([3,'车票详情'])
Z([3,'5cfdbaed-1'])
Z([3,'g-bg data-v-45106d39'])
Z(z[2])
Z(z[0])
Z([3,'5cfdbaed-2'])
Z([[4],[[5],[1,'default']]])
Z([3,'trip-box data-v-45106d39'])
Z([3,'trip-list data-v-45106d39'])
Z([3,'trip-item data-v-45106d39'])
Z([3,'item-top u-flex u-row-between u-flex-wrap data-v-45106d39'])
Z([3,'top-lf u-flex data-v-45106d39'])
Z([3,'name data-v-45106d39'])
Z([a,[[6],[[7],[3,'detailData']],[3,'ticketName']]])
Z([[6],[[7],[3,'detailData']],[3,'ticketCategoryName']])
Z([3,'tag tagMonth u-flex data-v-45106d39'])
Z([3,'img _img data-v-45106d39'])
Z([3,'/static/icon_monthlyPass.png'])
Z([3,'txt data-v-45106d39'])
Z([a,[[6],[[7],[3,'detailData']],[3,'ticketCategoryName']]])
Z([[2,'==='],[[6],[[7],[3,'detailData']],[3,'putTicketType']],[1,1]])
Z([3,'top-rg spot data-v-45106d39'])
Z([a,[[2,'+'],[[2,'+'],[1,''],[[6],[[7],[3,'$root']],[3,'m0']]],[1,'']]])
Z([[2,'==='],[[6],[[7],[3,'detailData']],[3,'putTicketType']],[1,2]])
Z([3,'top-rg data-v-45106d39'])
Z([[2,'==='],[[6],[[7],[3,'detailData']],[3,'ticketEffectiveType']],[1,1]])
Z([3,'spot data-v-45106d39'])
Z([a,[[2,'+'],[[2,'+'],[[2,'+'],[[2,'+'],[1,''],[[6],[[7],[3,'$root']],[3,'m1']]],[1,'\n                至\n                ']],[[6],[[7],[3,'$root']],[3,'m2']]],[1,'']]])
Z([[6],[[7],[3,'$root']],[3,'g0']])
Z(z[32])
Z([[2,'==='],[[6],[[7],[3,'detailData']],[3,'ticketEffectiveTypeSon']],[1,1]])
Z(z[0])
Z([a,[[2,'+'],[[6],[[7],[3,'$root']],[3,'m3']],[1,' 当日有效']]])
Z([[2,'==='],[[6],[[7],[3,'detailData']],[3,'ticketEffectiveTypeSon']],[1,2]])
Z(z[0])
Z([a,[[2,'+'],[[2,'+'],[1,'有效时长：'],[[6],[[7],[3,'detailData']],[3,'ticketEffectiveHour']]],[1,'小时']]])
Z([3,'item-con data-v-45106d39'])
Z([3,'lineTag-box data-v-45106d39'])
Z([3,'index2'])
Z([3,'item2'])
Z([[6],[[7],[3,'detailData']],[3,'lineList']])
Z(z[44])
Z([3,'lineTag-item data-v-45106d39'])
Z([3,'lineTag data-v-45106d39'])
Z(z[18])
Z([a,[[6],[[7],[3,'item2']],[3,'lineCode']]])
Z(z[0])
Z([3,'往'])
Z([3,'endStationName data-v-45106d39'])
Z([a,[[6],[[7],[3,'item2']],[3,'endStationName']]])
Z(z[0])
Z([3,'方向'])
Z([[2,'!'],[[6],[[7],[3,'item2']],[3,'limitSeatMark']]])
Z([3,'__e'])
Z([3,'c-primary u-m-l-15 data-v-45106d39'])
Z([[4],[[5],[[4],[[5],[[5],[1,'tap']],[[4],[[5],[[4],[[5],[[5],[[5],[1,'handServeTime']],[[4],[[5],[1,'$0']]]],[[4],[[5],[[4],[[5],[[4],[[5],[[5],[[5],[[5],[1,'detailData.lineList']],[1,'']],[[7],[3,'index2']]],[1,'lineId']]]]]]]]]]]]]]])
Z([3,'服务时间'])
Z(z[59])
Z(z[60])
Z([[4],[[5],[[4],[[5],[[5],[1,'tap']],[[4],[[5],[[4],[[5],[[5],[[5],[1,'handRealTime']],[[4],[[5],[1,'$0']]]],[[4],[[5],[[4],[[5],[[4],[[5],[[5],[[5],[1,'detailData.lineList']],[1,'']],[[7],[3,'index2']]]]]]]]]]]]]]]])
Z([3,'实时位置'])
Z(z[26])
Z([3,'info-place u-flex data-v-45106d39'])
Z([3,'place-lf flex-sub u-flex u-row-between data-v-45106d39'])
Z([3,'lf data-v-45106d39'])
Z([3,'u-flex u-col-top data-v-45106d39'])
Z([3,'tag data-v-45106d39'])
Z([3,'上'])
Z(z[0])
Z(z[18])
Z([a,[[6],[[7],[3,'detailData']],[3,'upStationName']]])
Z([[6],[[7],[3,'detailData']],[3,'upStationTime']])
Z([3,'time data-v-45106d39'])
Z([a,[[2,'+'],[1,'预计'],[[6],[[7],[3,'detailData']],[3,'upStationTime']]]])
Z([3,'place-rg flex-sub u-flex u-row-between data-v-45106d39'])
Z(z[70])
Z(z[71])
Z(z[72])
Z([3,'下'])
Z(z[0])
Z(z[18])
Z([a,[[6],[[7],[3,'detailData']],[3,'downStationName']]])
Z([[6],[[7],[3,'detailData']],[3,'downStationTime']])
Z(z[78])
Z([a,[[2,'+'],[1,'预计'],[[6],[[7],[3,'detailData']],[3,'downStationTime']]]])
Z([[2,'&&'],[[2,'==='],[[6],[[7],[3,'detailData']],[3,'putTicketType']],[1,2]],[[6],[[7],[3,'detailData']],[3,'needBookMark']]])
Z([3,'lineTotal u-flex data-v-45106d39'])
Z([3,'lf flex-sub data-v-45106d39'])
Z([3,'sum data-v-45106d39'])
Z([a,[[6],[[7],[3,'detailData']],[3,'bookTimes']]])
Z(z[18])
Z([3,'已预约次数'])
Z([3,'rg flex-sub data-v-45106d39'])
Z(z[94])
Z([a,[[6],[[7],[3,'detailData']],[3,'remainingRidingTimes']]])
Z(z[18])
Z([3,'剩余可预约次数'])
Z([[2,'&&'],[[2,'==='],[[6],[[7],[3,'detailData']],[3,'putTicketType']],[1,2]],[[2,'!'],[[6],[[7],[3,'detailData']],[3,'needBookMark']]]])
Z(z[92])
Z(z[93])
Z(z[94])
Z([a,[[6],[[7],[3,'detailData']],[3,'ridingTimes']]])
Z(z[18])
Z([3,'已乘车次数'])
Z(z[98])
Z(z[94])
Z([a,z[100][1]])
Z(z[18])
Z([3,'剩余可乘车次数'])
Z([[6],[[7],[3,'detailData']],[3,'passengerId']])
Z([3,'passenger-list data-v-45106d39'])
Z([3,'passenger-item u-flex data-v-45106d39'])
Z([3,'passenger-lf u-flex data-v-45106d39'])
Z(z[0])
Z([3,'u-flex data-v-45106d39'])
Z(z[18])
Z([a,[[6],[[7],[3,'detailData']],[3,'passengerName']]])
Z(z[0])
Z(z[72])
Z([a,[[6],[[7],[3,'$root']],[3,'g1']]])
Z([3,'card data-v-45106d39'])
Z([3,'u-m-r-10 data-v-45106d39'])
Z([3,'身份证'])
Z(z[0])
Z([a,[[6],[[7],[3,'detailData']],[3,'passengerIdCard']]])
Z([3,'record-box data-v-45106d39'])
Z([3,'record-list data-v-45106d39'])
Z(z[59])
Z([3,'record-item u-flex u-row-between data-v-45106d39'])
Z([[4],[[5],[[4],[[5],[[5],[1,'tap']],[[4],[[5],[[4],[[5],[[5],[1,'handGoto']],[[4],[[5],[1,2]]]]]]]]]]])
Z([3,'lf u-flex data-v-45106d39'])
Z(z[22])
Z([3,'/static/icon_riding.png'])
Z(z[18])
Z([3,'乘车记录'])
Z([3,'rg data-v-45106d39'])
Z(z[94])
Z([a,[[6],[[7],[3,'detailData']],[3,'ridingRecordCount']]])
Z(z[2])
Z(z[0])
Z([3,'#CCCCCC'])
Z([3,'16'])
Z([3,'right'])
Z([[2,'+'],[[2,'+'],[1,'5cfdbaed-3'],[1,',']],[1,'5cfdbaed-2']])
Z([[6],[[7],[3,'$root']],[3,'g2']])
Z([3,'footer-box data-v-45106d39'])
Z([3,'footer u-flex u-row-between data-v-45106d39'])
Z(z[59])
Z([3,'button rg w-fill data-v-45106d39'])
Z([[4],[[5],[[4],[[5],[[5],[1,'tap']],[[4],[[5],[[4],[[5],[[5],[1,'handGoto']],[[4],[[5],[1,3]]]]]]]]]]])
Z([3,'true'])
Z([3,'primary'])
Z([3,'乘车码'])
Z(z[2])
Z(z[59])
Z([3,'data-v-45106d39 vue-ref'])
Z([[4],[[5],[[4],[[5],[[5],[1,'^change']],[[4],[[5],[[4],[[5],[1,'handCheckResult']]]]]]]]])
Z([3,'qrPopup'])
Z([3,'5cfdbaed-4'])
Z(z[2])
Z(z[161])
Z([3,'serveTimePopup'])
Z([3,'5cfdbaed-5'])
})(__WXML_GLOBAL__.ops_cached.$gwx_XC_31_1);return __WXML_GLOBAL__.ops_cached.$gwx_XC_31_1
}
__WXML_GLOBAL__.ops_set.$gwx_XC_31=z;
__WXML_GLOBAL__.ops_init.$gwx_XC_31=true;
var x=['./pages/serve/ticketDetail/index.wxml'];d_[x[0]]={}
var m0=function(e,s,r,gg){
var z=gz$gwx_XC_31_1()
var eDXB=_n('view')
_rz(z,eDXB,'class',0,e,s,gg)
var bEXB=_mz(z,'top-bar',['background',1,'bind:__l',1,'class',2,'color',3,'isBack',4,'title',5,'vueId',6],[],e,s,gg)
_(eDXB,bEXB)
var oFXB=_n('view')
_rz(z,oFXB,'class',8,e,s,gg)
_(eDXB,oFXB)
var xGXB=_mz(z,'g-container',['bind:__l',9,'class',1,'vueId',2,'vueSlots',3],[],e,s,gg)
var cJXB=_n('view')
_rz(z,cJXB,'class',13,e,s,gg)
var hKXB=_n('view')
_rz(z,hKXB,'class',14,e,s,gg)
var oLXB=_n('view')
_rz(z,oLXB,'class',15,e,s,gg)
var cMXB=_n('view')
_rz(z,cMXB,'class',16,e,s,gg)
var aPXB=_n('view')
_rz(z,aPXB,'class',17,e,s,gg)
var eRXB=_n('text')
_rz(z,eRXB,'class',18,e,s,gg)
var bSXB=_oz(z,19,e,s,gg)
_(eRXB,bSXB)
_(aPXB,eRXB)
var tQXB=_v()
_(aPXB,tQXB)
if(_oz(z,20,e,s,gg)){tQXB.wxVkey=1
var oTXB=_n('view')
_rz(z,oTXB,'class',21,e,s,gg)
var xUXB=_mz(z,'image',['class',22,'src',1],[],e,s,gg)
_(oTXB,xUXB)
var oVXB=_n('text')
_rz(z,oVXB,'class',24,e,s,gg)
var fWXB=_oz(z,25,e,s,gg)
_(oVXB,fWXB)
_(oTXB,oVXB)
_(tQXB,oTXB)
}
tQXB.wxXCkey=1
_(cMXB,aPXB)
var oNXB=_v()
_(cMXB,oNXB)
if(_oz(z,26,e,s,gg)){oNXB.wxVkey=1
var cXXB=_n('view')
_rz(z,cXXB,'class',27,e,s,gg)
var hYXB=_oz(z,28,e,s,gg)
_(cXXB,hYXB)
_(oNXB,cXXB)
}
var lOXB=_v()
_(cMXB,lOXB)
if(_oz(z,29,e,s,gg)){lOXB.wxVkey=1
var oZXB=_n('view')
_rz(z,oZXB,'class',30,e,s,gg)
var c1XB=_v()
_(oZXB,c1XB)
if(_oz(z,31,e,s,gg)){c1XB.wxVkey=1
var l3XB=_n('view')
_rz(z,l3XB,'class',32,e,s,gg)
var a4XB=_oz(z,33,e,s,gg)
_(l3XB,a4XB)
_(c1XB,l3XB)
}
var o2XB=_v()
_(oZXB,o2XB)
if(_oz(z,34,e,s,gg)){o2XB.wxVkey=1
var t5XB=_n('view')
_rz(z,t5XB,'class',35,e,s,gg)
var e6XB=_v()
_(t5XB,e6XB)
if(_oz(z,36,e,s,gg)){e6XB.wxVkey=1
var o8XB=_n('text')
_rz(z,o8XB,'class',37,e,s,gg)
var x9XB=_oz(z,38,e,s,gg)
_(o8XB,x9XB)
_(e6XB,o8XB)
}
var b7XB=_v()
_(t5XB,b7XB)
if(_oz(z,39,e,s,gg)){b7XB.wxVkey=1
var o0XB=_n('text')
_rz(z,o0XB,'class',40,e,s,gg)
var fAYB=_oz(z,41,e,s,gg)
_(o0XB,fAYB)
_(b7XB,o0XB)
}
e6XB.wxXCkey=1
b7XB.wxXCkey=1
_(o2XB,t5XB)
}
c1XB.wxXCkey=1
o2XB.wxXCkey=1
_(lOXB,oZXB)
}
oNXB.wxXCkey=1
lOXB.wxXCkey=1
_(oLXB,cMXB)
var cBYB=_n('view')
_rz(z,cBYB,'class',42,e,s,gg)
var oFYB=_n('view')
_rz(z,oFYB,'class',43,e,s,gg)
var lGYB=_v()
_(oFYB,lGYB)
var aHYB=function(eJYB,tIYB,bKYB,gg){
var xMYB=_n('view')
_rz(z,xMYB,'class',48,eJYB,tIYB,gg)
var oNYB=_n('view')
_rz(z,oNYB,'class',49,eJYB,tIYB,gg)
var cPYB=_n('text')
_rz(z,cPYB,'class',50,eJYB,tIYB,gg)
var hQYB=_oz(z,51,eJYB,tIYB,gg)
_(cPYB,hQYB)
_(oNYB,cPYB)
var oRYB=_n('text')
_rz(z,oRYB,'class',52,eJYB,tIYB,gg)
var cSYB=_oz(z,53,eJYB,tIYB,gg)
_(oRYB,cSYB)
_(oNYB,oRYB)
var oTYB=_n('text')
_rz(z,oTYB,'class',54,eJYB,tIYB,gg)
var lUYB=_oz(z,55,eJYB,tIYB,gg)
_(oTYB,lUYB)
_(oNYB,oTYB)
var aVYB=_n('text')
_rz(z,aVYB,'class',56,eJYB,tIYB,gg)
var tWYB=_oz(z,57,eJYB,tIYB,gg)
_(aVYB,tWYB)
_(oNYB,aVYB)
var fOYB=_v()
_(oNYB,fOYB)
if(_oz(z,58,eJYB,tIYB,gg)){fOYB.wxVkey=1
var eXYB=_mz(z,'text',['catchtap',59,'class',1,'data-event-opts',2],[],eJYB,tIYB,gg)
var bYYB=_oz(z,62,eJYB,tIYB,gg)
_(eXYB,bYYB)
_(fOYB,eXYB)
}
var oZYB=_mz(z,'text',['catchtap',63,'class',1,'data-event-opts',2],[],eJYB,tIYB,gg)
var x1YB=_oz(z,66,eJYB,tIYB,gg)
_(oZYB,x1YB)
_(oNYB,oZYB)
fOYB.wxXCkey=1
_(xMYB,oNYB)
_(bKYB,xMYB)
return bKYB
}
lGYB.wxXCkey=2
_2z(z,46,aHYB,e,s,gg,lGYB,'item2','index2','index2')
_(cBYB,oFYB)
var hCYB=_v()
_(cBYB,hCYB)
if(_oz(z,67,e,s,gg)){hCYB.wxVkey=1
var o2YB=_n('view')
_rz(z,o2YB,'class',68,e,s,gg)
var f3YB=_n('view')
_rz(z,f3YB,'class',69,e,s,gg)
var c4YB=_n('view')
_rz(z,c4YB,'class',70,e,s,gg)
var h5YB=_n('view')
_rz(z,h5YB,'class',71,e,s,gg)
var o6YB=_n('view')
_rz(z,o6YB,'class',72,e,s,gg)
var c7YB=_oz(z,73,e,s,gg)
_(o6YB,c7YB)
_(h5YB,o6YB)
var o8YB=_n('view')
_rz(z,o8YB,'class',74,e,s,gg)
var a0YB=_n('view')
_rz(z,a0YB,'class',75,e,s,gg)
var tAZB=_oz(z,76,e,s,gg)
_(a0YB,tAZB)
_(o8YB,a0YB)
var l9YB=_v()
_(o8YB,l9YB)
if(_oz(z,77,e,s,gg)){l9YB.wxVkey=1
var eBZB=_n('view')
_rz(z,eBZB,'class',78,e,s,gg)
var bCZB=_oz(z,79,e,s,gg)
_(eBZB,bCZB)
_(l9YB,eBZB)
}
l9YB.wxXCkey=1
_(h5YB,o8YB)
_(c4YB,h5YB)
_(f3YB,c4YB)
_(o2YB,f3YB)
var oDZB=_n('view')
_rz(z,oDZB,'class',80,e,s,gg)
var xEZB=_n('view')
_rz(z,xEZB,'class',81,e,s,gg)
var oFZB=_n('view')
_rz(z,oFZB,'class',82,e,s,gg)
var fGZB=_n('view')
_rz(z,fGZB,'class',83,e,s,gg)
var cHZB=_oz(z,84,e,s,gg)
_(fGZB,cHZB)
_(oFZB,fGZB)
var hIZB=_n('view')
_rz(z,hIZB,'class',85,e,s,gg)
var cKZB=_n('view')
_rz(z,cKZB,'class',86,e,s,gg)
var oLZB=_oz(z,87,e,s,gg)
_(cKZB,oLZB)
_(hIZB,cKZB)
var oJZB=_v()
_(hIZB,oJZB)
if(_oz(z,88,e,s,gg)){oJZB.wxVkey=1
var lMZB=_n('view')
_rz(z,lMZB,'class',89,e,s,gg)
var aNZB=_oz(z,90,e,s,gg)
_(lMZB,aNZB)
_(oJZB,lMZB)
}
oJZB.wxXCkey=1
_(oFZB,hIZB)
_(xEZB,oFZB)
_(oDZB,xEZB)
_(o2YB,oDZB)
_(hCYB,o2YB)
}
var oDYB=_v()
_(cBYB,oDYB)
if(_oz(z,91,e,s,gg)){oDYB.wxVkey=1
var tOZB=_n('view')
_rz(z,tOZB,'class',92,e,s,gg)
var ePZB=_n('view')
_rz(z,ePZB,'class',93,e,s,gg)
var bQZB=_n('view')
_rz(z,bQZB,'class',94,e,s,gg)
var oRZB=_oz(z,95,e,s,gg)
_(bQZB,oRZB)
_(ePZB,bQZB)
var xSZB=_n('view')
_rz(z,xSZB,'class',96,e,s,gg)
var oTZB=_oz(z,97,e,s,gg)
_(xSZB,oTZB)
_(ePZB,xSZB)
_(tOZB,ePZB)
var fUZB=_n('view')
_rz(z,fUZB,'class',98,e,s,gg)
var cVZB=_n('view')
_rz(z,cVZB,'class',99,e,s,gg)
var hWZB=_oz(z,100,e,s,gg)
_(cVZB,hWZB)
_(fUZB,cVZB)
var oXZB=_n('view')
_rz(z,oXZB,'class',101,e,s,gg)
var cYZB=_oz(z,102,e,s,gg)
_(oXZB,cYZB)
_(fUZB,oXZB)
_(tOZB,fUZB)
_(oDYB,tOZB)
}
var cEYB=_v()
_(cBYB,cEYB)
if(_oz(z,103,e,s,gg)){cEYB.wxVkey=1
var oZZB=_n('view')
_rz(z,oZZB,'class',104,e,s,gg)
var l1ZB=_n('view')
_rz(z,l1ZB,'class',105,e,s,gg)
var a2ZB=_n('view')
_rz(z,a2ZB,'class',106,e,s,gg)
var t3ZB=_oz(z,107,e,s,gg)
_(a2ZB,t3ZB)
_(l1ZB,a2ZB)
var e4ZB=_n('view')
_rz(z,e4ZB,'class',108,e,s,gg)
var b5ZB=_oz(z,109,e,s,gg)
_(e4ZB,b5ZB)
_(l1ZB,e4ZB)
_(oZZB,l1ZB)
var o6ZB=_n('view')
_rz(z,o6ZB,'class',110,e,s,gg)
var x7ZB=_n('view')
_rz(z,x7ZB,'class',111,e,s,gg)
var o8ZB=_oz(z,112,e,s,gg)
_(x7ZB,o8ZB)
_(o6ZB,x7ZB)
var f9ZB=_n('view')
_rz(z,f9ZB,'class',113,e,s,gg)
var c0ZB=_oz(z,114,e,s,gg)
_(f9ZB,c0ZB)
_(o6ZB,f9ZB)
_(oZZB,o6ZB)
_(cEYB,oZZB)
}
hCYB.wxXCkey=1
oDYB.wxXCkey=1
cEYB.wxXCkey=1
_(oLXB,cBYB)
_(hKXB,oLXB)
_(cJXB,hKXB)
_(xGXB,cJXB)
var oHXB=_v()
_(xGXB,oHXB)
if(_oz(z,115,e,s,gg)){oHXB.wxVkey=1
var hA1B=_n('view')
_rz(z,hA1B,'class',116,e,s,gg)
var oB1B=_n('view')
_rz(z,oB1B,'class',117,e,s,gg)
var cC1B=_n('view')
_rz(z,cC1B,'class',118,e,s,gg)
var oD1B=_n('view')
_rz(z,oD1B,'class',119,e,s,gg)
var lE1B=_n('view')
_rz(z,lE1B,'class',120,e,s,gg)
var aF1B=_n('text')
_rz(z,aF1B,'class',121,e,s,gg)
var tG1B=_oz(z,122,e,s,gg)
_(aF1B,tG1B)
_(lE1B,aF1B)
var eH1B=_n('view')
_rz(z,eH1B,'class',123,e,s,gg)
var bI1B=_n('text')
_rz(z,bI1B,'class',124,e,s,gg)
var oJ1B=_oz(z,125,e,s,gg)
_(bI1B,oJ1B)
_(eH1B,bI1B)
_(lE1B,eH1B)
_(oD1B,lE1B)
var xK1B=_n('view')
_rz(z,xK1B,'class',126,e,s,gg)
var oL1B=_n('text')
_rz(z,oL1B,'class',127,e,s,gg)
var fM1B=_oz(z,128,e,s,gg)
_(oL1B,fM1B)
_(xK1B,oL1B)
var cN1B=_n('text')
_rz(z,cN1B,'class',129,e,s,gg)
var hO1B=_oz(z,130,e,s,gg)
_(cN1B,hO1B)
_(xK1B,cN1B)
_(oD1B,xK1B)
_(cC1B,oD1B)
_(oB1B,cC1B)
_(hA1B,oB1B)
_(oHXB,hA1B)
}
var oP1B=_n('view')
_rz(z,oP1B,'class',131,e,s,gg)
var cQ1B=_n('view')
_rz(z,cQ1B,'class',132,e,s,gg)
var oR1B=_mz(z,'view',['bindtap',133,'class',1,'data-event-opts',2],[],e,s,gg)
var lS1B=_n('view')
_rz(z,lS1B,'class',136,e,s,gg)
var aT1B=_mz(z,'image',['class',137,'src',1],[],e,s,gg)
_(lS1B,aT1B)
var tU1B=_n('text')
_rz(z,tU1B,'class',139,e,s,gg)
var eV1B=_oz(z,140,e,s,gg)
_(tU1B,eV1B)
_(lS1B,tU1B)
_(oR1B,lS1B)
var bW1B=_n('view')
_rz(z,bW1B,'class',141,e,s,gg)
var oX1B=_n('text')
_rz(z,oX1B,'class',142,e,s,gg)
var xY1B=_oz(z,143,e,s,gg)
_(oX1B,xY1B)
_(bW1B,oX1B)
var oZ1B=_mz(z,'uni-icons',['bind:__l',144,'class',1,'color',2,'size',3,'type',4,'vueId',5],[],e,s,gg)
_(bW1B,oZ1B)
_(oR1B,bW1B)
_(cQ1B,oR1B)
_(oP1B,cQ1B)
_(xGXB,oP1B)
var fIXB=_v()
_(xGXB,fIXB)
if(_oz(z,150,e,s,gg)){fIXB.wxVkey=1
var f11B=_n('view')
_rz(z,f11B,'class',151,e,s,gg)
var c21B=_n('view')
_rz(z,c21B,'class',152,e,s,gg)
var h31B=_mz(z,'button',['bindtap',153,'class',1,'data-event-opts',2,'plain',3,'type',4],[],e,s,gg)
var o41B=_oz(z,158,e,s,gg)
_(h31B,o41B)
_(c21B,h31B)
_(f11B,c21B)
_(fIXB,f11B)
}
oHXB.wxXCkey=1
fIXB.wxXCkey=1
_(eDXB,xGXB)
var c51B=_mz(z,'g-qr-popup',['bind:__l',159,'bind:change',1,'class',2,'data-event-opts',3,'data-ref',4,'vueId',5],[],e,s,gg)
_(eDXB,c51B)
var o61B=_mz(z,'g-serve-time-popup',['bind:__l',165,'class',1,'data-ref',2,'vueId',3],[],e,s,gg)
_(eDXB,o61B)
_(r,eDXB)
return r
}
e_[x[0]]={f:m0,j:[],i:[],ti:[],ic:[]}
if(path&&e_[path]){
outerGlobal.__wxml_comp_version__=0.02
return function(env,dd,global){$gwxc=0;var root={"tag":"wx-page"};root.children=[]
;g="$gwx_XC_31";var main=e_[path].f
if (typeof global==="undefined")global={};global.f=$gdc(f_[path],"",1);
if(typeof(outerGlobal.__webview_engine_version__)!='undefined'&&outerGlobal.__webview_engine_version__+1e-6>=0.02+1e-6&&outerGlobal.__mergeData__)
{
env=outerGlobal.__mergeData__(env,dd);
}
try{
main(env,{},root,global);
_tsd(root)
if(typeof(outerGlobal.__webview_engine_version__)=='undefined'|| outerGlobal.__webview_engine_version__+1e-6<0.01+1e-6){return _ev(root);}
}catch(err){
console.log(err)
}
;g="";
return root;
}
}
}
}(__g.a,__g.b,__g.c,__g.d,__g.e,__g.f,__g.g,__g.h,__g.i,__g.j,__g.k,__g.l,__g.m,__g.n,__g.o,__g.p,__g.q,__g.r,__g.s,__g.t,__g.u,__g.v,__g.w,__g.x,__g.y,__g.z,__g.A,__g.B,__g.C,__g.D,__g.E,__g.F,__g.G,__g.H,__g.I,__g.J,__g.K,__g.L,__g.M,__g.N,__g.O,__g.P,__g.Q,__g.R,__g.S,__g.T,__g.U,__g.V,__g.W,__g.X,__g.Y,__g.Z,__g.aa);if(__vd_version_info__.delayedGwx||false)$gwx_XC_31();	if (__vd_version_info__.delayedGwx) __wxAppCode__['pages/serve/ticketDetail/index.wxml'] = [$gwx_XC_31, './pages/serve/ticketDetail/index.wxml'];else __wxAppCode__['pages/serve/ticketDetail/index.wxml'] = $gwx_XC_31( './pages/serve/ticketDetail/index.wxml' );
	
var noCss=typeof __vd_version_info__!=='undefined'&&__vd_version_info__.noCss===true;if(!noCss){__wxAppCode__['pages/serve/ticketDetail/index.wxss']=setCssToHead([".",[1],"trip-box.",[1],"data-v-45106d39{margin-top:",[0,32],";padding:0 ",[0,32],"}\n.",[1],"trip-box .",[1],"trip-list .",[1],"trip-item.",[1],"data-v-45106d39{background:#fff;border-radius:",[0,16]," ",[0,16]," ",[0,16]," ",[0,16],";margin-bottom:",[0,24],";padding:",[0,24]," ",[0,32],"}\n.",[1],"trip-box .",[1],"trip-list .",[1],"trip-item .",[1],"item-top .",[1],"top-lf .",[1],"name.",[1],"data-v-45106d39{color:rgba(0,0,0,.9);font-size:",[0,32],";font-weight:500}\n.",[1],"trip-box .",[1],"trip-list .",[1],"trip-item .",[1],"item-top .",[1],"top-lf .",[1],"tag.",[1],"data-v-45106d39{background:#ffe5d8;border-radius:",[0,8]," ",[0,8]," ",[0,8]," ",[0,8],";margin:0 ",[0,16],";padding:",[0,4]," ",[0,8],"}\n.",[1],"trip-box .",[1],"trip-list .",[1],"trip-item .",[1],"item-top .",[1],"top-lf .",[1],"tag .",[1],"img.",[1],"data-v-45106d39{height:",[0,24],";margin-right:",[0,8],";width:",[0,24],"}\n.",[1],"trip-box .",[1],"trip-list .",[1],"trip-item .",[1],"item-top .",[1],"top-lf .",[1],"tag .",[1],"txt.",[1],"data-v-45106d39{color:#ff3f3f;font-size:",[0,22],";font-weight:400}\n.",[1],"trip-box .",[1],"trip-list .",[1],"trip-item .",[1],"item-top .",[1],"top-lf .",[1],"tagMonth.",[1],"data-v-45106d39{background:#e3f9e9}\n.",[1],"trip-box .",[1],"trip-list .",[1],"trip-item .",[1],"item-top .",[1],"top-lf .",[1],"tagMonth .",[1],"txt.",[1],"data-v-45106d39{color:#2ba471}\n.",[1],"trip-box .",[1],"trip-list .",[1],"trip-item .",[1],"item-top .",[1],"top-rg.",[1],"data-v-45106d39{color:rgba(0,0,0,.6);font-size:",[0,24],";font-weight:400}\n.",[1],"trip-box .",[1],"trip-list .",[1],"trip-item .",[1],"item-con .",[1],"lineTag-box.",[1],"data-v-45106d39{margin-bottom:",[0,12],";margin-top:",[0,18],"}\n.",[1],"trip-box .",[1],"trip-list .",[1],"trip-item .",[1],"item-con .",[1],"lineTag-box .",[1],"lineTag-item.",[1],"data-v-45106d39{margin-top:",[0,8],";width:100%}\n.",[1],"trip-box .",[1],"trip-list .",[1],"trip-item .",[1],"item-con .",[1],"lineTag-box .",[1],"lineTag-item .",[1],"lineTag.",[1],"data-v-45106d39{-webkit-align-items:center;align-items:center;background:rgba(0,0,0,.02);border:",[0,1]," solid rgba(0,0,0,.26);border-radius:",[0,8]," ",[0,8]," ",[0,8]," ",[0,8],";color:rgba(0,0,0,.6);display:-webkit-inline-flex;display:inline-flex;font-size:",[0,24],";max-width:calc(100% - ",[0,32],");padding:",[0,4]," ",[0,16],";white-space:nowrap}\n.",[1],"trip-box .",[1],"trip-list .",[1],"trip-item .",[1],"item-con .",[1],"lineTag-box .",[1],"lineTag-item .",[1],"lineTag .",[1],"name.",[1],"data-v-45106d39{color:rgba(0,0,0,.9);display:inline-block;font-size:",[0,28],"!important;font-weight:600;margin-right:",[0,8],";max-width:",[0,180],";overflow:hidden;text-overflow:ellipsis;white-space:nowrap}\n.",[1],"trip-box .",[1],"trip-list .",[1],"trip-item .",[1],"item-con .",[1],"lineTag-box .",[1],"lineTag-item .",[1],"lineTag .",[1],"endStationName.",[1],"data-v-45106d39{display:inline-block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}\n.",[1],"trip-box .",[1],"trip-list .",[1],"trip-item .",[1],"item-con .",[1],"lineTag-box .",[1],"lineTag-item .",[1],"active.",[1],"data-v-45106d39{background:#e8f1ff;border:",[0,1]," solid #1972fb;border-radius:",[0,8]," ",[0,8]," ",[0,8]," ",[0,8],";color:#1972fb;font-size:",[0,24],"}\n.",[1],"trip-box .",[1],"trip-list .",[1],"trip-item .",[1],"item-con .",[1],"lineTotal.",[1],"data-v-45106d39{background:#fafafa;border-radius:",[0,8]," ",[0,8]," ",[0,8]," ",[0,8],";padding:",[0,24],"}\n.",[1],"trip-box .",[1],"trip-list .",[1],"trip-item .",[1],"item-con .",[1],"lineTotal .",[1],"lf.",[1],"data-v-45106d39{border-right:",[0,2]," solid #f4f4f4}\n.",[1],"trip-box .",[1],"trip-list .",[1],"trip-item .",[1],"item-con .",[1],"lineTotal .",[1],"lf.",[1],"data-v-45106d39,.",[1],"trip-box .",[1],"trip-list .",[1],"trip-item .",[1],"item-con .",[1],"lineTotal .",[1],"rg.",[1],"data-v-45106d39{text-align:center}\n.",[1],"trip-box .",[1],"trip-list .",[1],"trip-item .",[1],"item-con .",[1],"lineTotal .",[1],"sum.",[1],"data-v-45106d39{color:#1972fb;font-size:",[0,34],";font-weight:600;margin-bottom:",[0,8],"}\n.",[1],"trip-box .",[1],"trip-list .",[1],"trip-item .",[1],"item-con .",[1],"lineTotal .",[1],"name.",[1],"data-v-45106d39{color:rgba(0,0,0,.6);font-size:",[0,28],";font-weight:400}\n.",[1],"trip-box .",[1],"trip-list .",[1],"trip-item .",[1],"item-con .",[1],"info-place.",[1],"data-v-45106d39{background:#fafafa;border-radius:",[0,16],";margin-top:",[0,24],"}\n.",[1],"trip-box .",[1],"trip-list .",[1],"trip-item .",[1],"item-con .",[1],"info-place .",[1],"place-lf.",[1],"data-v-45106d39,.",[1],"trip-box .",[1],"trip-list .",[1],"trip-item .",[1],"item-con .",[1],"info-place .",[1],"place-rg.",[1],"data-v-45106d39{padding:",[0,24]," ",[0,28],"}\n.",[1],"trip-box .",[1],"trip-list .",[1],"trip-item .",[1],"item-con .",[1],"info-place .",[1],"place-lf .",[1],"tag.",[1],"data-v-45106d39,.",[1],"trip-box .",[1],"trip-list .",[1],"trip-item .",[1],"item-con .",[1],"info-place .",[1],"place-rg .",[1],"tag.",[1],"data-v-45106d39{background:#4cb11b;border-radius:50%;color:#fff;font-size:",[0,16],";font-weight:400;height:",[0,32],";line-height:",[0,30],";margin-right:",[0,8],";padding:",[0,4],";text-align:center;width:",[0,32],"}\n.",[1],"trip-box .",[1],"trip-list .",[1],"trip-item .",[1],"item-con .",[1],"info-place .",[1],"place-lf .",[1],"name.",[1],"data-v-45106d39,.",[1],"trip-box .",[1],"trip-list .",[1],"trip-item .",[1],"item-con .",[1],"info-place .",[1],"place-rg .",[1],"name.",[1],"data-v-45106d39{color:rgba(0,0,0,.8);font-size:",[0,26],";font-weight:500;margin-bottom:",[0,8],";white-space:nowrap}\n.",[1],"trip-box .",[1],"trip-list .",[1],"trip-item .",[1],"item-con .",[1],"info-place .",[1],"place-lf .",[1],"time.",[1],"data-v-45106d39,.",[1],"trip-box .",[1],"trip-list .",[1],"trip-item .",[1],"item-con .",[1],"info-place .",[1],"place-rg .",[1],"time.",[1],"data-v-45106d39{color:rgba(0,0,0,.4);font-size:",[0,24],";font-weight:400}\n.",[1],"trip-box .",[1],"trip-list .",[1],"trip-item .",[1],"item-con .",[1],"info-place .",[1],"place-rg .",[1],"tag.",[1],"data-v-45106d39{background-color:#f35827}\n.",[1],"record-box.",[1],"data-v-45106d39{margin-top:",[0,24],";padding:0 ",[0,32],"}\n.",[1],"record-box .",[1],"record-list.",[1],"data-v-45106d39{background:#fff;border-radius:",[0,16],"}\n.",[1],"record-box .",[1],"record-list .",[1],"record-item.",[1],"data-v-45106d39{border-bottom:",[0,2]," solid #f4f4f4;padding:",[0,26]," ",[0,32],"}\n.",[1],"record-box .",[1],"record-list .",[1],"record-item.",[1],"data-v-45106d39:last-child{border-bottom:none}\n.",[1],"record-box .",[1],"record-list .",[1],"record-item .",[1],"lf.",[1],"data-v-45106d39{color:rgba(0,0,0,.9);font-size:",[0,32],";font-weight:400}\n.",[1],"record-box .",[1],"record-list .",[1],"record-item .",[1],"lf .",[1],"img.",[1],"data-v-45106d39{height:",[0,40],";margin-right:",[0,22],";width:",[0,40],"}\n.",[1],"record-box .",[1],"record-list .",[1],"record-item .",[1],"lf .",[1],"name.",[1],"data-v-45106d39{color:#000;font-size:",[0,32],";font-weight:400;line-height:",[0,38],"}\n.",[1],"record-box .",[1],"record-list .",[1],"record-item .",[1],"lf .",[1],"coupon.",[1],"data-v-45106d39{color:rgba(0,0,0,.9)}\n.",[1],"record-box .",[1],"record-list .",[1],"record-item .",[1],"rg .",[1],"sum.",[1],"data-v-45106d39{color:rgba(0,0,0,.6);font-size:",[0,30],";font-weight:400}\n.",[1],"passenger-list.",[1],"data-v-45106d39{margin-top:",[0,24],";padding:0 ",[0,32],"}\n.",[1],"passenger-list .",[1],"passenger-item.",[1],"data-v-45106d39{background:#fff;border-radius:",[0,16],";padding:",[0,26]," ",[0,32],"}\n.",[1],"passenger-list .",[1],"passenger-item .",[1],"passenger-lf .",[1],"name.",[1],"data-v-45106d39{color:rgba(0,0,0,.9);font-size:",[0,30],";font-weight:500}\n.",[1],"passenger-list .",[1],"passenger-item .",[1],"passenger-lf .",[1],"tag.",[1],"data-v-45106d39{background:rgba(0,0,0,.02);border:",[0,1]," solid rgba(0,0,0,.26);border-radius:",[0,8]," ",[0,8]," ",[0,8]," ",[0,8],";color:rgba(0,0,0,.6);font-size:",[0,18],";font-weight:400;margin-left:",[0,12],";padding:",[0,4]," ",[0,8],"}\n.",[1],"passenger-list .",[1],"passenger-item .",[1],"passenger-lf .",[1],"restrict.",[1],"data-v-45106d39{color:#f54a32;font-size:",[0,24],";font-weight:400;margin-left:",[0,12],"}\n.",[1],"passenger-list .",[1],"passenger-item .",[1],"passenger-lf .",[1],"card.",[1],"data-v-45106d39{color:rgba(0,0,0,.6);font-size:",[0,24],";font-weight:400;margin-top:",[0,8],"}\n.",[1],"footer-box .",[1],"footer.",[1],"data-v-45106d39{height:",[0,152],"}\n.",[1],"footer-box .",[1],"lf.",[1],"data-v-45106d39{background-color:#fff;border:",[0,2]," solid #165dff;border-radius:",[0,200]," ",[0,200]," ",[0,200]," ",[0,200],";color:#165dff;font-size:",[0,30],";font-weight:400}\n",],undefined,{path:"./pages/serve/ticketDetail/index.wxss"});
}